### ISSUE TITLE
Add command-line option for enabling the NSFW filter

### ISSUE THREAD

**Issue by skorokithakis** [brycedrennan/imaginAIry#10]
Currently, the NSFW filter cannot be disabled if you're using the `imagine` command (at least I haven't found how). Since mostly everyone wants the filter off, it would be good if the default were off and it had an option to enable it.

**Comment by brycedrennan** [comment]
Having it off by default would lead to a very jarring experiences for unsuspecting users.  It's intentionally not documented how to disable it but if you poke around in the code you can figure it out.

**Comment by skorokithakis** [comment]
It's certainly clear how to turn it off in the code, the issue is that, if I want to install this on a server to generate images, I'd have to either fiddle with the files in the container and try to somehow make it automatic, or I'd have to fork the repo. Changing the source after installation is pretty inconvenient in automated deployments :(

**Comment by brycedrennan** [comment]
It's already deployed on servers. No source code modification is necessary.  

Apologies for being vague, I normally like to be as helpful as possible, but I don't want to document this aspect of the software. If you reach out privately I'm happy to be more specific.

**Comment by skorokithakis** [comment]
Ah, understandable, thank you.
