### ISSUE TITLE
Mac M1 Building wheel for lmdb (setup.py) ... error

### ISSUE THREAD

**Issue by bitcoinvsalts** [brycedrennan/imaginAIry#100]
After running:

`pip install ~/Downloads/artifact/grpcio-1.50.0-cp39-cp39-macosx_11_0_arm64.whl
`

`pip install imaginairy` is giving me this error:

` Building wheel for tokenizers (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/anaconda3/bin/python /opt/homebrew/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/c1/ljxqhkyd1qzgg4qk3jvhs7wh0000gn/T/tmpo9j7y_x4
       cwd: /private/var/folders/c1/ljxqhkyd1qzgg4qk3jvhs7wh0000gn/T/pip-install-b25b4xs6/tokenizers_dd0925788dc24426ab75f773b7cae81d
  Complete output (51 lines):
  running bdist_wheel
...
ERROR: Failed building wheel for tokenizers
  Building wheel for lmdb (setup.py) ... error
  ERROR: Command errored out with exit status 1:
...
`

any idea why?

I used the binary because `pip install imaginairy` was not working.

**Comment by brycedrennan** [comment]
conda is not supported. I should add that to the docs

**Comment by bitcoinvsalts** [comment]
so it does not work with M1?

**Comment by brycedrennan** [comment]
It'll work with regular ol' python.

**Comment by bitcoinvsalts** [comment]
how can i use the regular ol' python, not the conda variant?

**Comment by brycedrennan** [comment]
Lot's of different options. I use pyenv

https://www.python.org/downloads/macos/
https://docs.python-guide.org/starting/install3/osx/
https://github.com/pyenv/pyenv

**Comment by bitcoinvsalts** [comment]
Thank you for your prompt replies 🙏🏼

**Comment by smart-patrol** [comment]
I ran in to the same issue here and pyenv/virtual env did not help.
Running the instructions in [this post did](https://stackoverflow.com/questions/71671666/error-command-usr-bin-clang-failed-with-exit-code-1).
