### ISSUE TITLE
train the model with personal photos

### ISSUE THREAD

**Issue by AntouanK** [brycedrennan/imaginAIry#104]
Is there a simple way to train the model with photos of ourselves?
Like give it a name and 10 photos, so it knows how a specific person looks like.

**Comment by brycedrennan** [comment]
This repo doesn't help with that but if you google "textual inversion" or "stable diffusion dreambooth" you should find what you're looking for.

**Comment by AntouanK** [comment]
Yeah, I did look into it.

If I take the model out, re-train it and replace it back, it should work, right?
Where is the ckpt model file located when running imaginairy?

**Comment by brycedrennan** [comment]
you can tell imaginairy to use a different ckpt with `--model-weights-path`

**Comment by AntouanK** [comment]
would this one work?

https://huggingface.co/stabilityai/stable-diffusion-2/blob/main/768-v-ema.ckpt

**Comment by brycedrennan** [comment]
@AntouanK that one works and is included in the latest `imaginairy` if you just say `--model SD-2.1-v`
