### ISSUE TITLE
Upscaling with SD 2.0

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [brycedrennan/imaginAIry#109]
Thank you for making such an amazing repo and for having SD 2.0 available in such a small period. I tested SD 2.0 and it works well but I can't scale the 768x768 images with upscale=True. I get no errors.

**Comment by brycedrennan** [comment]
Interesting I hadn't tried that out yet.
Please provide the following information:
imaginairy version
python version 
OS
GPU + GPU RAM

**Comment by brycedrennan** [comment]
I tried it just now. Upscaling worked. Did you noticed that they're going to the "upscaled" folder.

**Comment by ahmed-mohamed-sn** [comment]
My mistake, I was accessing result.img and not result.upscaled_img. The results look great.

**Comment by brycedrennan** [comment]
docs could be better on this. thanks!
