### ISSUE TITLE
minor: metadata (or filename) update to record model being used

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#110]
currently 'Content Creator' (exif) in output images contains 'Imaginairy / Stable Diffusion v1.4'
I was looking for somewhere to record which model has been used during generation (now we have 3, and it appears v2 is significantly different to 1.4/5) and on the filename would be obvious but might require more effort and if anything 'downstream' is relying on filenames might cause other issues... still it's probably to most obvious place to record it..

Even 'lower hanging fruit' option - 'Content Creator' is already there in image metadata and could just have a 'switch-board' added to change model from 1.4->1.5->2.0 in text as required..

thoughts?

**Comment by brycedrennan** [comment]
yeah that's an oversight. nice catch
