### ISSUE TITLE
Request: ability to feed in multiple input images

### ISSUE THREAD

**Issue by reubenfirmin** [brycedrennan/imaginAIry#115]
Please consider adding the ability to add multiple input images. Let's say you're working from an original photo, and generate a bunch of semi-random variations of it. It would be great to be able to resubmit the original with the 2 or 3 strongest variants.

From my naive reading of the code, this may be possible here:

```
                            rebuilt_orig_img = Image.composite(
                                prompt.init_image,
                                img_to_add_back_to_original,
                                mask_for_orig_size,
                            )
```

**Comment by reubenfirmin** [comment]
As an extension to this, an alternate mode could allow seeding the model with a random combination from a pool of provided images. You have 10 good variants from a batch; now use them to generate 100 new variants.

**Comment by brycedrennan** [comment]
Thanks for the suggestion.

This sounds too specific of a case to handle for a python library, and mostly sounds like something better suited to a GUI.  Wouldn't be too hard to write a python script to do that but selecting the input images would be tedious without a GUI.

**Comment by reubenfirmin** [comment]
@brycedrennan Totally fair if you wish to remain a "no" on this, but as a followon:

I think the command line is absolutely the right place for this, and opens up a really powerful editing experience. I have an image gallery (gwenview) to see (and organize) the generated images. That's all I need. What would be great would be e.g. the ability to work on different components of a composition in separation generations. For example, let's say you wanted a space monster destroying a city; you could try to generate it all in one shot, but maybe in all of the generations either the city or the space monster sucks.

What I'd love here is the ability to say something like (with perhaps better syntax):

`--init-images [ {image: space_monster_37.jpg, mask: "monster NOT background"}, {image: city_skyline_23.jpg, mask: "skyscrapers NOT sky"} ] --blend-mode compose`



Can that be done?
