### ISSUE TITLE
Request: Masking with low init-image-strength should be allowed to move the masked area in the output

### ISSUE THREAD

**Issue by reubenfirmin** [brycedrennan/imaginAIry#116]
When using a mask, the masked area always stays in the exact same place. With a low init-image-strength (and/or a new mask parameter) the area should be allowed to be scaled and moved. 

For example, with a closeup of a face, it should be possible to generate outputs that are "zoomed out" and have a body attached.

**Comment by brycedrennan** [comment]
It sounds like you're asking for outpainting.  To do what you describe you'd just place shrunk down image where desired and then mask everything in the image.  I may eventually add some helper functions to assist with that.

**Comment by reubenfirmin** [comment]
Part of what's great about the models is that they can come up with novel "ideas" - I'm not requesting outpainting, but rather the ability for the masked area to be adjusted by random seed in whatever way is feasible. If I for example want "dog's head on person's body" with a mask of "dog's head", then the model should be able to put the head on a short person, a tall person, a person walking down a street, a person driving a car, whatever. The mask function currently overly restricts the text prompt; it would be nice if it could also serve as just an input. Text prompt = idea; mask = resource to be used in the idea, without any restriction on size, position.

**Comment by brycedrennan** [comment]
This could be accomplished via an integration with the openai api but is outside the scope of this library.
