### ISSUE TITLE
add negative prompt feature

### ISSUE THREAD

**Issue by adityapurwa** [brycedrennan/imaginAIry#123]
# Using Negative Prompts

First, I would like to say thank you for making this project.

I would like to know how to specify negative prompts to the `imagine` script. I tried searching for how to do it on the readme and on the code but couldn't find it. Can you please help by providing guides on how to specify negative prompts?

Thank you!

**Comment by brycedrennan** [comment]
Negative prompts has not yet been implemented. Apparently it's important now though for 2.0, so it should probably be added.

**Comment by adityapurwa** [comment]
> Negative prompts has not yet been implemented. Apparently it's important now though for Stable Diffusion 2.0, so it should probably be added.

Thank you for the explanation. I don't have much experience with Python, but let me know if I can help with anything else (docs, samples, etc) on this.

**Comment by Cybergate9** [comment]
I was also interested in this for same reason (i.e nice for 1.5, but apparently almost required to get good results out of 2.0)
Started poking around to see implementation details for this from elsewhere and the 'base' implementation seems to orginal in automatic1111 not surprisingly, and there quite a good explanation of that implementation here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Negative-prompt

assume you'd probably already seen it, but thought I'd post as possible helper in case not..

**Comment by brycedrennan** [comment]
Released in 7.0.0.  `--negative-prompt`. a decent default is now used if you do not provide one.
