### ISSUE TITLE
make versions based on git tags and add --version to command line options

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#126]
it comes up often enough (in issues comments) that its probably worth adding a:
--version
command line option

or at least output the version number with --help?

what do you think?

**Comment by brycedrennan** [comment]
Yes that makes sense.  It's a bit more involved than you might expect because the version number doesn't exist inside the package currently.

**Comment by Cybergate9** [comment]
can it be done by looking at its own installation? i.e. I tend to look at folder name at 
/<snip>/py-venv3/lib/python3.10/site-packages/imaginAIry-7.0.0.dist-info
to figure out what version I've got installed, so looking for 'regex' like match on site-packages/imaginAIry-(X.X.X).dist-info should always report local installation number?
a bit 'cludgy' but if version/release numbers are maintained in github & pip then just looking for their metadata in a local install seems reasonable?

**Comment by brycedrennan** [comment]
I can't with 100% confidence say what you propose won't work, but I don't believe it will for the many different kinds of possible python installations.  

What I've done in other libraries is hookup `setuptools_scm` and have it write a file `version.py` at package build time.  Then you can just `from imaginairy.version import version` and add it as an option on the command line client.

**Comment by Cybergate9** [comment]
Ah.. that sounds a much more reliable way of getting version metadata into release code during build.. and should be bullet-proof :-)

**Comment by brycedrennan** [comment]
I added `imagine --version` and `aimg version` in just released 7.6.0
