### ISSUE TITLE
integrate with Apple CoreML

### ISSUE THREAD

**Issue by Booli** [brycedrennan/imaginAIry#132]
Amazing work! 

I read about the CoreML implementation by Apple, is it possible to integrate that into ImaginAIry? 
https://github.com/apple/ml-stable-diffusion

**Comment by brycedrennan** [comment]
That would be nice. Seems like it's based on diffusers though. Not sure how plausible integration is.

**Comment by iandol** [comment]
See https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5309

**Comment by dalaohuniu** [comment]
good idea

**Comment by iandol** [comment]
Some issues for context from another python SD tool: https://github.com/invoke-ai/InvokeAI/issues/2167 and https://github.com/invoke-ai/InvokeAI/issues/1676 and https://huggingface.co/TheMurusTeam/coreml-upscaler-realesrgan512

**Comment by brycedrennan** [comment]
Thanks @iandol

**Comment by brycedrennan** [comment]
https://twitter.com/pcuenq/status/1620080393226706945

**Comment by brycedrennan** [comment]
I don't see a path for this to happen unless someone makes a python api to the swift versions. Will re-open if something changes in this space.

**Comment by 9Somboon** [comment]
please.
