### ISSUE TITLE
aimg describe got FileNotFoundError

### ISSUE THREAD

**Issue by iwater** [brycedrennan/imaginAIry#14]
aimg describe outputs/000320_526397716_ddim40_PS7.5_ID_photo_of_a_child.jpg 

FileNotFoundError: [Errno 2] No such file or directory: '/home/iwater/miniconda3/envs/imaginAIry/lib/python3.10/site-packages/imaginairy/vendored/blip/configs/med_config.json'

**Comment by brycedrennan** [comment]
@jprobichaud @iwater there was a file missing and I just released the fix
