### ISSUE TITLE
wishlist - integrate 360 panoramas

### ISSUE THREAD

**Issue by wweevv-johndpope** [brycedrennan/imaginAIry#140]
https://github.com/FrozenBurning/Text2Light

background
https://github.com/tannakaken/vertigo-garden

**Comment by brycedrennan** [comment]
I would accept a pull request with this feature.  here is an example implementation: https://gist.github.com/jschoormans/7688ab4c88e0435c4dc0afe3f17dd969

**Comment by brycedrennan** [comment]
Having looked into this more the script basically boils down to what would be `--tile-horiontal`

**Comment by brycedrennan** [comment]
https://github.com/tjm35/asymmetric-tiling-sd-webui/blob/main/scripts/asymmetric_tiling.py 
this would be an example implementation

**Comment by johndpope** [comment]
👏 awesome
