### ISSUE TITLE
Automatic changelog

### ISSUE THREAD

**Issue by hannesa2** [brycedrennan/imaginAIry#147]
Are you interested in an automatic generated change log for a new release ?
If yes, I could make a pull request

**Comment by brycedrennan** [comment]
Can I see an example of a repo using that?

**Comment by hannesa2** [comment]
e.g https://github.com/gitx/gitx/releases/tag/0.21

**Comment by brycedrennan** [comment]
looks interesting. I can stop pushing to master directly.  

Only thing is it seems we'd need to. improve how the versions are managed in the package as well (since I'm manually editing the text now).  I like tag based setups but haven't taken the time to do that here yet.

**Comment by brycedrennan** [comment]
I'm not ready for this. Closing for now
