### ISSUE TITLE
No module named 'deep_daze'

### ISSUE THREAD

**Issue by paperbenni** [brycedrennan/imaginAIry#15]
After installation in a 3.10 virtualenv the imagine cli throws this error on first usage. 
```
hdddrive/python/ai via v3.10.7 (ai) $ imagine 'a dog'
Traceback (most recent call last):
  File "/usr/bin/imagine", line 5, in <module>
    from deep_daze.cli import main
ModuleNotFoundError: No module named 'deep_daze'
hdddrive/python/ai via v3.10.7 (ai) $
```
Even after `pip install deep_daze`  the error persists

**Comment by brycedrennan** [comment]
the error appears to be because `deep_daze` previously installed the `imagine` command.  I was unaware of this library or naming conflict. 

You could probably remove the file at /usr/bin/imagine and then reinstall imaginairy to get it working
