### ISSUE TITLE
 Feature request:add new option --xformers and --lowvram and --medvram

### ISSUE THREAD

**Issue by Gspohu** [brycedrennan/imaginAIry#157]
Hello everyone,

I suggest adding 3 new options to this great tool that is "imaginairy", in order to improve the performances:

- "--xformers" in order to use _**Xformers**_ library like in here : https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers

- "--medvram" Makes the Stable Diffusion model consume less VRAM by splitting it into three parts (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations)

- "--lowvram" An even more thorough optimization of the above, splitting unet into many modules (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations)

In my opinion, if you have to implement only one, it would be **_Xformers_**.

Thank you for reading me,

**Comment by brycedrennan** [comment]
**xformers**
I had xformers working not long ago. On my 2080 it was ~30% improvement (10it/s=>13its) Tried it just now and it didn't work - generated noise or black images. I do remember I had to manually tweak some things so not sure if I forgot something.   The specific commit referenced fixes an issue I had to manually fix when I previously got it working

```
PATH="/usr/local/cuda-11.6/bin:$PATH" \
LD_LIBRARY_PATH="/usr/local/cuda-11.6/lib64:$LD_LIBRARY_PATH" \
FORCE_CUDA="1" \
TORCH_CUDA_ARCH_LIST=8.6 \
pip install -v -U git+https://github.com/facebookresearch/xformers.git@e773f9dd362e64b810ac8597010169a2fa44b1db#egg=xformers
```

I don't plan on officially supporting xformers as it's too hard to install (I just spent ~2 hours trying to get it working again on my machine), which is against the "just works" ethos of this library.
**low memory operation**

Similarly, I don't plan on adding further memory usage improvements that add complexity to the codebase.  I occasionally check in on projects like xformers, voltaml, and colossalai to see if a "simple" integration is possible.  Those may help for low-memory situations.
