### ISSUE TITLE
change to work with less VRAM - "CUDA out of memory"

### ISSUE THREAD

**Issue by llagerlof** [brycedrennan/imaginAIry#16]
My graphics card is a NVIDIA GeForce GTX 1050 Ti, 4G memory.

When I run the `imagine` command I receive this error:

```
  File "/home/user1/.pyenv/versions/3.10.6/envs/imaginairy-3.10.6/lib/python3.10/site-packages/torch/nn/modules/module.py", line 925, in convert

    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 3.95 GiB total capacity; 2.82 GiB already allocated; 69.38 MiB free; 2.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  

See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I didn't find a minimum requirements in project's README, so I am assuming a 4G GPU isn't enough to run this application. However I was able to run [this stable diffusion project](https://github.com/cmdr2/stable-diffusion-ui), so I am hoping some configuration could solve this for imaginAlry.

**Comment by llagerlof** [comment]
Just to add some information, I found someone with the same problem, but his card is 8GB.

https://stackoverflow.com/questions/71498324/pytorch-runtimeerror-cuda-out-of-memory-with-a-huge-amount-of-free-memory

I am not a Python developer, so that thread doesn't helped me too much.

**Comment by brycedrennan** [comment]
Thanks. I'll see what can be done to optimise this.

**Comment by thoastbrot** [comment]
6GB 1060 runs fine if I close apps like chrome beforehand. There's no room for parallel GPU usage with such cards.

**Comment by brycedrennan** [comment]
@llagerlof Given there are so many features to add, I've decided to not prfioritize further memory efficiency. I'd suggest using a google colab or different project.

**Comment by llagerlof** [comment]
I understand. Thank you for the feedback.
