### ISSUE TITLE
[Requirements] What are the requirements of this?

### ISSUE THREAD

**Issue by ManuLinares** [brycedrennan/imaginAIry#164]
I'm trying to run this on a 32Gb Ram machine with a "1050TI 4GB VRAM".

The readme doesn't list min requirements for this, and it fails on my system.

I've run the blender addon "dreamtextures" with success.

**Comment by brycedrennan** [comment]
Yeah I don't know what the minimum GPU ram requirements are but 4gb is surely below them.  It runs on my 11gb 2080ti. I'll leave this open as a reminder to update the docs.

**Comment by brycedrennan** [comment]
Updated docs to say 11gb vram is required although it probaby runs with less.

**Comment by franz101** [comment]
For imagine replacement im running into ram errors on google colab

<img width="159" alt="Screenshot 2023-01-23 at 22 59 27" src="https://user-images.githubusercontent.com/18228395/214159409-8a9de4c6-add0-4e63-8044-5d16b62f02c9.png">
