### ISSUE TITLE
Parametrize Cache Model Files location

### ISSUE THREAD

**Issue by dreve** [brycedrennan/imaginAIry#168]
The current implementation uses the `~/.cache` folder to cache the model files.
It would be nice to have the ability to use a custom one via the command line.

I am having fun with imaginAIry on Windows (yea, I know, but it works) and I really don't want to fill my C:/ drive with models.

**Comment by brycedrennan** [comment]
Most (but probably not all) downloads use the transformers download functionality so theoretically setting `TRANSFORMERS_CACHE` env var should do the trick. 
https://stackoverflow.com/questions/63312859/how-to-change-huggingface-transformers-default-cache-directory

**Comment by Sebastian-Jung** [comment]
This worked for me:

Huggingface cache download folder can be changed with
```bash
export HF_DATASETS_CACHE="/path/to/another/directory"
```

source: https://huggingface.co/docs/huggingface_hub/how-to-cache
