### ISSUE TITLE
lower VRAM requirement

### ISSUE THREAD

**Issue by ManuLinares** [brycedrennan/imaginAIry#186]
Why: It would open up the user base to support **<=4gb VRAM**
https://store.steampowered.com/hwsurvey/videocard/
https://www.statista.com/statistics/265036/proportion-of-used-pcs-on-the-steam-by-video-memory/

How: _I don't know but_ I do know similar projects that work under 4gb vram like:

1. https://github.com/AUTOMATIC1111/stable-diffusion-webui/
1. https://github.com/carson-katri/dream-textures

**Comment by brycedrennan** [comment]
I'm open to changes that improve memory usage that do not add significant complexity to the codebase. If you have specific ideas in that regard I welcome them.

Time is limited so I currently don't intend on offering support for less VRAM intensive algorithms.

**Comment by Esfo** [comment]
can you add a flag to bypass the gpu for when you have a gpu but not enough vram? there seems to be cpu-based functionality that i've gotten to work, but only on a machine without a gpu

**Comment by brycedrennan** [comment]
I'm gonna make at attempt at improving memory usage.  I dont think I'll get it down to 4gb though.  Anyone available to test it?

**Comment by brycedrennan** [comment]
I think lower vram might be supported with just released 8.1.0
<img width="746" alt="vramXresolution" src="https://user-images.githubusercontent.com/1217531/214822350-be499393-98c7-4d4f-862c-2943eb16308d.png">

**Comment by brycedrennan** [comment]
@Esfo try env var `CUDA_VISIBLE_DEVICES=-1` - that might work.
