### ISSUE TITLE
feature request - subtraction by another image

### ISSUE THREAD

**Issue by johndpope** [brycedrennan/imaginAIry#19]
https://twitter.com/ygantigravity/status/1572357902354251776?s=20&t=TA_m3smm3h1YAtsEoil3sg

![image](https://user-images.githubusercontent.com/289994/191683881-eb90d14f-d0da-4d06-bcb1-cd247dd2ed57.png)

https://t.co/O5YGKXikf9

**Comment by brycedrennan** [comment]
Thanks for the idea. I've played around with this and I'm not sure I see how it would produce better results than just prompting with "female mario".   Is there some situation this is particularly well-suited to?

**Comment by brycedrennan** [comment]
I'll reopen if I hear about any compelling use cases.
