### ISSUE TITLE
Configurable Safety Argument

### ISSUE THREAD

**Issue by RichardMcSorley** [brycedrennan/imaginAIry#193]
I've noticed when using imaginairy I've had issues with the safety checker taking upwards of 60s so in some situations it might be worthwhile to disable or parametrize this functionality, especially if user is manually curating the results.

There does not seem to be a way to do this now. I've seen an environment variable defined but setting it to "disabled" does not have an effect.

**Comment by brycedrennan** [comment]
@RichardMcSorley I will not be changing this for legal and ethical reasons. I don't think you did anything wrong to request this so forgive me that I will be censoring this thread to the extent possible.
