### ISSUE TITLE
PNDM Scheduler | Diffusers

### ISSUE THREAD

**Issue by ghunkins** [brycedrennan/imaginAIry#196]
Thank you for creating such an incredible resource!

I am curious if this repo can replicate the default scheduler for `diffusers`: PNDM. I know that PLMS and PNDM are just aliases, but I get different results via diffusers when I pin the seed vs. this repository.

[**Diffusers PNDM Scheduler Pipeline**](https://github.com/huggingface/diffusers/blob/a66f2baeb782e091dde4e1e6394e46f169e5ba58/src/diffusers/schedulers/scheduling_pndm.py)

Is there a way for me to reproduce results from `diffusers` here?

We are interested in incorporating this repo into the work done on https://mage.space, but we need to be able to have backwards compatibility with settings and seeds.

**Comment by brycedrennan** [comment]
Producing same images for same seed with diffusers is not a feature I want to support. I expect it would be a lot of work and isn't something most people care about. I don't think I can even promise seed stability across my own versions or across machines.   

If I'm wrong and it's not that hard I'd be happy to have more consistent outputs. So if someone knows a trick or wants to submit a PR i'd take a look.
