### ISSUE TITLE
Colab fails

### ISSUE THREAD

**Issue by webdevserv** [brycedrennan/imaginAIry#197]
Initial installs and pip installs OK, running colab with 1 GPU but it fails to import the libraries of imaginairy(imaginAIry)

!pip uninstall -y torchtext 
!pip install imaginairy==8.0.0 pillow --upgrade
!nvidia-smi -L
!pip freeze | grep -i pillow

_________________FAILS in line 1----------------------
from imaginairy import imagine, imagine_image_files, ImaginePrompt, WeightedPrompt, LazyLoadingImage
from imaginairy.log_utils import configure_logging

configure_logging()

**Comment by brycedrennan** [comment]
you have to restart the instance (it says so in the colab)

**Comment by webdevserv** [comment]
Oh yes thanks, it says start a new session on a header. It is not intuitive
at all to read that and to guess that the below code won't work.
This bug can be made into huge capital letters in the colab header and
commented in code.

**Comment by brycedrennan** [comment]
I've changed it so that it restarts itself

**Comment by webdevserv** [comment]
cheers
