### ISSUE TITLE
can be extremely slow if running in unsupported CPU mode

### ISSUE THREAD

**Issue by brycedrennan** [brycedrennan/imaginAIry#20]
When I force it to run on CPU it runs extremely slow.  Sounds similar to what's described here:

https://github.com/pytorch/pytorch/issues/75458

**Comment by brycedrennan** [comment]
Meh. Lets just not support old CPUs.

**Comment by devingfx** [comment]
Hi!
If someone have no choices but use CPU, said "extremely slow runs" are  bettrer than "time is money" ,  can it be forced to run on CPU only mode? For every models inference, SD, but also ControlNet, ESRGANs, ect ?

**Comment by brycedrennan** [comment]
Does it not already work that way?

**Comment by devingfx** [comment]
I dunno ^^ !
I asked before testing the install... you know searching for a SD integration that work on CPU, I tested several systems, downloading everything, envs, modls, etc... for nothing, so now I prefer ask before !

Is it a "It should work, never tested" or a "Yes, we tested each commands 1 by 1 and all pass without a CUDA device perfectly :+1: " ?
:smile:
