### ISSUE TITLE
How much memory do I need to run it?

### ISSUE THREAD

**Issue by trappedinspacetime** [brycedrennan/imaginAIry#201]
I am on Ubuntu 22.04 platform. I have a laptop ryzen5 5500u with 8gb of RAM. 
I tried many examples but all of them failed and killed by system  because it consumes all of the RAM.

**Comment by brycedrennan** [comment]
It's GPU memory that matters most. 11 gb of GPU ram should be sufficient. It's not really intended to run on the CPU or non-cuda enabled graphics cards.

**Comment by titlestad** [comment]
What about the news it could run on 6GB?
