### ISSUE TITLE
document how to change model directory

### ISSUE THREAD

**Issue by GitEin11** [brycedrennan/imaginAIry#214]
is there a way to change default directory for models

**Comment by brycedrennan** [comment]
Like where they get cached?

**Comment by GitEin11** [comment]
> 

yes, because my os partition will be out of space

**Comment by brycedrennan** [comment]
Apologies for the slow response. Since the cache is almost entirely using huggingface these directions should work:
https://huggingface.co/docs/huggingface_hub/how-to-cache

In short, set the `HUGGINGFACE_HUB_CACHE` environment variable

**Comment by brycedrennan** [comment]
I've added this to the readme file
