### ISSUE TITLE
Copyright of received images

### ISSUE THREAD

**Issue by mpfmorawski** [brycedrennan/imaginAIry#217]
Hello, I would like to ask about the copyright of images received using the library. I understand that the software is under the MIT license (which allows commercial use, among other things). However, does this license also apply to the generated images? Or, alternatively, where could I learn more about this topic?

**Comment by Titaniumtown** [comment]
This is uncharted territory legally. Wait a while and some court cases will come up. You'll have your answer then.

**Comment by brycedrennan** [comment]
I am not a lawyer so consider the following opinion worthless:

In my opinion, whoever "clicked the button" owns the work.  I don't think it's really uncharted territory but it's good media story if we say it is.  We've had advanced image editing tools for years and no one has been "but you didn't manually pick each individual pixel, maybe photoshop owns the copyright for the pixels it made for you".  This is just another tool.   

I would read the stable diffusion license to start with: https://huggingface.co/spaces/CompVis/stable-diffusion-license

**Comment by mpfmorawski** [comment]
Thank you very much for your responses.
