### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by steamcards** [brycedrennan/imaginAIry#226]
Hello! I have next prompt on generation (under Windows):

> received 1 prompt(s) and will repeat them 1 times to create 1 images.
> Running in CPU mode. it's gonna be slooooooow.

Is there a way to enable CUDA GPU?

**Comment by brycedrennan** [comment]
It will automatically use cuda if it's available. I'd refer you to torch installation instructions: https://pytorch.org/ and that you make sure you have an appropriate graphics card and cuda drivers installed.

**Comment by bjwie** [comment]
hey @brycedrennan,
first of all, fanstatic job!
I would recommand that you put this infomation in the readme.
