### ISSUE TITLE
How to keep original image size on edition

### ISSUE THREAD

**Issue by xzitlou** [brycedrennan/imaginAIry#227]
I'm running something like the sample:
```
aimg edit --gif --surprise-me spock.jpg
```

But the result has different size, how can I keep the same original size?
Thanks

**Comment by xzitlou** [comment]
I tried adding:
```
-height={height} --width={width}
```
and it's returning:
```
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function
```

**Comment by brycedrennan** [comment]
what is the output of `aimg system-info` Are you trying to run on CPU only?

**Comment by brycedrennan** [comment]
Running at larger sizes will not work well and be very slow. The algorithm is only intended for sizes close to 512

**Comment by xzitlou** [comment]
I tried reducing the size:
```
aimg edit "sprite.jpg" "remove microphone" --height=2840 --width=1600 --outdir=files
```
The output is
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 225.35 GiB (GPU 0; 20.00 GiB total capacity; 3.36 GiB already allocated; 10.77 GiB free; 6.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
it's a memory issue..

**Comment by brycedrennan** [comment]
Yeah that “reduced” size is waay too big. As I said it’s intended for 512px images.  Try it at 512 and then upscale the image with ‘aimg upscale”

**Comment by xzitlou** [comment]
Hello again.. I'm trying a 512px image but it's returning a brown image:
`ImaginePrompt(
    prompt=terms,
    model="edit",
    init_image=LazyLoadingImage(filepath=sprite),
    mask_mode="replace",
    fix_faces=True,
    height=height,
    width=width,
)`

**Comment by brycedrennan** [comment]
try setting `init_image_strength=0`
