### ISSUE TITLE
Consider creating a directory for images to be batch-edited

### ISSUE THREAD

**Issue by IAmJonoBo** [brycedrennan/imaginAIry#229]
It would be helpful to speed up testing if users could create a local directory for images for batch testing and review.

**Comment by brycedrennan** [comment]
Will change the edit interface to accept  multiple files. Terminal globbing should do the work after that. Not sure if that works for windows

**Comment by brycedrennan** [comment]
`aimg edit` can now accept multiple input images in just released 9.0.0
