### ISSUE TITLE
Feature request: REPL mode

### ISSUE THREAD

**Issue by dfyx** [brycedrennan/imaginAIry#23]
The most time-consuming step seems to be startup and loading the model. On my system (Ubuntu 20.04 in WSL on Windows 10, Ryzen 3600X, RTX 3080), startup takes about 11 seconds compared to about 3-4 seconds for the actual image generation (at 40 steps).

It would be nice to have a REPL-like mode where the script stays running and you can enter new prompts and options until you explicitly quit. This would speed up generating a bunch of different images a lot.

**Comment by brycedrennan** [comment]
totally agree. do you have any suggestions for how to most easily accomplish that?

**Comment by dfyx** [comment]
I'm not a python dev  so I'm a bit hazy on the details but for an initial version it should be enough to just implement a loop that takes a line from stdin, parses them as if they were given as command line args and execute the same code as usual minus the initalization. Repeat until the user types something like "quit".

For most languages, there are some nice stdin wrappers that allow using arrow keys to navigate previous inputs and maybe even do autocompletion (have a look at something like GNU readline which might be available in python).

**Comment by thoastbrot** [comment]
https://docs.python.org/3/library/cmd.html this might be the way.

**Comment by brycedrennan** [comment]
@thoastbrot what do you mean a setup for each run?

**Comment by brycedrennan** [comment]
@dfyx I just added this feature and released it a few minutes ago.

https://pypi.org/project/imaginAIry/

After updating you run the command `aimg` and the interactive terminal starts up.  Can't say I tested it much so I appreciate any feedback you have.

**Comment by brycedrennan** [comment]
@thoastbrot the models are only loaded once if you're using REPL mode

**Comment by dfyx** [comment]
Seems to work really well. Thanks a lot!
