### ISSUE TITLE
What are the equivalent commands for  image CFG weight and text CFG weight ?

### ISSUE THREAD

**Issue by G-force78** [brycedrennan/imaginAIry#236]
So to troubleshoot the results as described here

https://github.com/timothybrooks/instruct-pix2pix#tips

**Comment by brycedrennan** [comment]
text cfg is `--prompt-strength` and image CFG is not configurable in imaginairy. It's hardcoded to 1.5 in the code here: https://github.com/brycedrennan/imaginAIry/blob/master/imaginairy/samplers/editing.py#L25.  I haven't found this to be a significant limitation as messing with the text CFG has seemed to be sufficient so far.  Would be interesting to learn if this is important.
