### ISSUE TITLE
command line CLI broken on windows as of version 9.0.0

### ISSUE THREAD

**Issue by tcgumus** [brycedrennan/imaginAIry#239]
Hello,
When i try to run "imagine ' a robot'" it asks me "how do you want to open this file" on windows 22h2. Problem occured after i updated Imaginary package. 

![image](https://user-images.githubusercontent.com/2714346/216853081-0046f546-4e31-46b2-a5ff-b4a5f92b7090.png)

Can you help me on that? 

I see the file changed 2 days ago. Maybe I'm missing something here. https://github.com/brycedrennan/imaginAIry/blob/master/imaginairy/bin/imagine

**Comment by brycedrennan** [comment]
Sorry I don't support windows. I'm not sure what the problem would be. Looks like it can't find the file. I'd check that you're able to run any python-based tool.  Is that powershell? Does it work with `pip install imaginairy<9.0.0` ?

**Comment by tcgumus** [comment]
Yes any other package is working. 
I did pip install imaginairy<9.0.0 and deleted files (imagine and aimg) from C:\Program Files\Python310\Scripts. Now it is working fine.

**Comment by brycedrennan** [comment]
well darn. even though I don't support it officially I'd like that to work. can you show me the error messages (they were covered by that dialogue box).

**Comment by tcgumus** [comment]
sorry but it doesn't give any error message. Just opens a popup `How do you want to open this file` (like in the first picture) when executing command. I reverse engineered a little bit and found out it opens imagine file in `C:\Program Files\Python310\Scripts` folder. Deleted everthing and tried again and got the same error. Tried on differen computer and got the same error. Tried to run in old cmd and couldn't got `no such file or directory` error. 
Other errors in the first picture i shared just me messing around 😄

**Comment by brycedrennan** [comment]
okay well dumb question on my part but... how do you install python on windows. I know I can look it up, but want to use the same method you did.

**Comment by tcgumus** [comment]
I just installed it via https://www.python.org/downloads/

**Comment by brycedrennan** [comment]
okay I'll take a look

**Comment by tcgumus** [comment]
thank you 💯

**Comment by brycedrennan** [comment]
:shakes-fist: windows! yeah I see the new scripts approach I took doesn't work for windows

Here is my horrible powershell workaround:

```powershell
python (Get-Command pip).Path.replace("pip.exe", "aimg") imagine pizza
```

**Comment by brycedrennan** [comment]
I've just released 9.0.1 which *might* fix this.  Never release a windows specific version before 🤞 .  Let me know.

**Comment by brycedrennan** [comment]
Fixed it on my windows machine. Also I'd suggest using https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-us&gl=us&rtc=1 as it will actually display the emoji and will look nicer generally

**Comment by tcgumus** [comment]
Hello, 
Tried 9.0.2 and it is working fine. 👍  You are the best! Thank you for fast response.

**Comment by ColinTalksCrypto** [comment]
I installed imaginAIry in Windows as well. Thank you for the update.

One issue I have is that I cannot get it to use my video card. I have a GeForce 4070 TI with 12gb ram.

I successfully installed imaginAIry and it will run. But it will only run in CPU-only mode. I even installed CUDA v11, but  imaginAIry won't use it for some reason.
![image](https://user-images.githubusercontent.com/44652168/217060819-73c4ee27-2b9f-49a0-82a5-7f0b859f1939.png)

**Comment by ColinTalksCrypto** [comment]
> I had the same error and solved by following this issue comment. [#66 (comment)](https://github.com/brycedrennan/imaginAIry/issues/66#issuecomment-1332782864) @ColinTalksCrypto

Thank you so much! I will try this and see if it fixes things. I'll report back either way.

**Comment by ColinTalksCrypto** [comment]
Success!! Following those instructions you linked to, made it so my Windows installation of ImaginAIry now uses my GPU. Thank you so much, @tcgumus !
