### ISSUE TITLE
A way to save the depth_image as png?

### ISSUE THREAD

**Issue by Limbicnation** [brycedrennan/imaginAIry#242]
Hi, great tool!
is there a way to save the `depth_image` as .png?

Thanks in advance!

regards,
Gero

**Comment by brycedrennan** [comment]
the recently added `--output-file-extension png` will do that

**Comment by Limbicnation** [comment]
Thank you!

**Comment by Limbicnation** [comment]
@brycedrennan Excuse me for asking once more, but could you guide me on how to configure the dimensions for the depth image?
