### ISSUE TITLE
concept-training (aka Dreambooth)

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#245]
Running on Tesla T4, 16GB, ran out of memory after first Epoch

 warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been de
precated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(

🤖🧠 Training "photo of billhamilton man" based on 10 images.

Continue? [y/N]: y
IMG_1317.jpg:   0%|                                                                                                                                                       | 0/10 [00:00<?, ?it/s]
/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use '
weights' instead.
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be re
moved in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
IMG_1319.jpg: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.05it/s]
Continue? [y/N]: y
Continue? [y/N]: y

Missing logger folder: ./lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 123 M
---------------------------------------------------------
859 M     Trainable params
206 M     Non-trainable params
1.1 B     Total params
4,264.941 Total estimated model params size (MB)
/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers whi
ch may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1609: PossibleUserWarning: The number of training batches (20) is smaller than the logging interval Trainer(
log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                            | 0/20 [00:00<?, ?it/s]
/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/data.py:84: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1.
 To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:232: UserWarning: You called `self.log('global_step', ...)` in your `training_ste
p` but the value needs to be floating point. Converting it to torch.float32.
  warning_cache.warn(
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:09<00:00,  2.15it/s]
Epoch 0:  95%|████▊| 19/20 [01:17<00:04,  4.07s/it, loss=0.168, v_num=0, train/loss_simple_step=0.00617, train/loss_vlb_step=3.32e-5, train/loss_step=0.00617, global_step=0.000, lr_abs=3.2e-11]
[W reducer.cpp:1298] Warning: find_unused_

    state['exp_avg_sq'] = torch.zeros_like(p, memory_format=torch.preserve_format)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 14.62 GiB total capacity; 13.33 GiB already allocated; 27.94 MiB free; 13.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Epoch 0:  95%|█████████▌| 19/20 [03:31<00:11, 11.12s/it, loss=0.168, v_num=0, train/loss_simple_step=0.00617, train/loss_vlb_step=3.32e-5, train/loss_step=0.00617, global_step=0.000, lr_abs=3.2e-11]

Any chance this can run on a 16GB GPU?

**Comment by bluusun** [comment]
BTW some good ideas here to push size below 16GB https://github.com/huggingface/diffusers/tree/main/examples/dreambooth

**Comment by brycedrennan** [comment]
I should remove this feature as I think there are better options out there. probably i wont put more time into it

**Comment by bluusun** [comment]
OK!
