### ISSUE TITLE
Combining several mask items

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#249]
This works very well for me:

--mask-prompt "faces {*11} "  --mask-mode keep  

This does not work at all for me (neither faces nor arms are kept):

--mask-prompt "faces {*11} and arms {*11}"  --mask-mode keep  

What is the right syntax to keep faces and arms at same scale?

**Comment by brycedrennan** [comment]
i dont think thats the right syntax. syntax is here: https://github.com/brycedrennan/imaginAIry#prompt-based-masking--by-clipseg

**Comment by bluusun** [comment]
"(faces AND arms AND hands)  {*11}" ?

**Comment by bluusun** [comment]
My use case is not 100% covered by the samples I feel.

**Comment by bluusun** [comment]
Total brainfart :) Works now using OR :)
