### ISSUE TITLE
Several faces in images - only one recognized

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#250]
Two faces in image (both rather prominent and apart).

Using this mask now:

mask_prompt="(faces OR arms OR hands) {+11}",

Oddly the resulting image:

- one face perfectly kept
- all arms/hands kept well
- second person face is completely different every time

Any ideas what to improve?

**Comment by bluusun** [comment]
Prompt is portrait of two people ....

**Comment by brycedrennan** [comment]
You'll just have to try different things. It's not perfect for sure.  Maybe it wont work for that photo.

**Comment by bluusun** [comment]
I think it is related to the mask - can't get several items to combine via AND. OR delivers these inconsistent results. I can't find a syntax that works i.e. mask_prompt="(faces AND arms AND hands) {+11}" does not deliver what I want.
