### ISSUE TITLE
imaginAIry on Google Colab demo / example?

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#251]
I would like to simply run a test of imaginAIry module on Google Colab, but I cannot make so I enter the interactive mode like aimg, nor running imagine command line.

I wonder how I could run this actually on Google Colab?

**Comment by nonoesp** [comment]
Hi @enzyme69! Here's a simple [Colab Notebook to run imaginAIry ↗︎](https://colab.research.google.com/drive/14yX7hBoSn6mhOBYgDhYIbOX1mXpuDRpM?usp=sharing).

You can run commands that you would run on the command line with an exclamation mark `!`.

**Comment by brycedrennan** [comment]
nice thanks @nonoesp

**Comment by brycedrennan** [comment]
The colab works well now.
