### ISSUE TITLE
Python lib - Upscale / Upscale only mode

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#253]
I am using this upscale=True. I see this output:

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:16<00:00,  3.96it/s]
        Tile 1/2
        Tile 2/2

Saving it like that:

for result in imagine(prompts):
            i = random.randint(0, 2001)
            result.save(f"{img_out_folder}/{filename2}_{i}.jpg")

However the saved image seems the same as not upscaled. I know in cli mode it's in a different folder but how do I extract it with Python?

Also is there a an Upscale only mode? i.e. Use input image and upscale to HD/4K/8K?

**Comment by brycedrennan** [comment]
I have an open item to improve the documentation. Short of that I suggest looking through the codebase to see what functions are used. `api.py` is a good place to start.
