### ISSUE TITLE
how to cut out an object from photo?

### ISSUE THREAD

**Issue by netdur** [brycedrennan/imaginAIry#254]
hello, thanks for great software, would it possible to cut sticker from back of laptop and mate it in poster or just white background?

https://www.cnet.com/a/img/resize/216756bb187979891b34356ac9d686fc6ce1c9f4/hub/2016/10/13/7e9ebfc3-8b34-4359-9975-712a69d86bd1/laptopstickersshield.jpg?auto=webp&width=1200

I tried:  aimg edit .\sticker.webp -p "make sticker in white background poster" --prompt-strength 50 --steps 75

**Comment by brycedrennan** [comment]
i think that is beyond current capabilities.
