### ISSUE TITLE
Custom model huggingface support

### ISSUE THREAD

**Issue by federicotorrielli** [brycedrennan/imaginAIry#255]
It would be awesome to add support to custom models with model weights downloaded from Huggingface. An option like `--custom-model "andite/pastel-mix"`.

**Comment by brycedrennan** [comment]
Was a surprise to me but I think this already works if you just `--model url`
![015861_442555190_kdpmpp2m15_PS7 5_a_bowl_of_fruit_ generated](https://user-images.githubusercontent.com/1217531/221379610-f229f8bd-4445-414d-9da3-c72381f18b5e.jpg)

**Comment by bluusun** [comment]
I can't get this to work:

imagine --model https://huggingface.co/nicky007/stable-diffusion-logo-fine-tuned "Logo of a pirate"

  File "/home/ubuntu/.local/lib/python3.8/site-packages/imaginairy/model_manager.py", line 452, in extract_huggingface_repo_commit_file_from_url
    assert path_components[2] == "resolve"
IndexError: list index out of range

Downloaded it and ran like this:

imagine --model 1.ckpt "Logo of a pirate"

	size mismatch for model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for model.diffusion_model.output_blocks.11.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).

Does that one need conversion?

Struggling to find the right script/usage...

https://github.com/huggingface/diffusers/tree/main/scripts

**Comment by brycedrennan** [comment]
`imagine --model https://huggingface.co/nicky007/stable-diffusion-logo-fine-tuned "Logo of a pirate"`
wouldn't work because you need to link to the actual weights.  

As far as the second error, it looks like this is in the diffusers format.  I know conversion is possible but I've never personally done it.  just by the name I'd start here: https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py

**Comment by bluusun** [comment]
Trying this one now:

imagine --model https://huggingface.co/22h/vintedois-diffusion-v0-1/ "person in a forest"

    assert path_components[2] == "resolve"
IndexError: list index out of range

**Comment by bluusun** [comment]
Worked after download :)

**Comment by brycedrennan** [comment]
For it to work you need to put the url for the weights:
--model https://huggingface.co/22h/vintedois-diffusion-v0-1/resolve/main/model.ckpt

**Comment by bluusun** [comment]
Works like a charm!
