### ISSUE TITLE
List of models

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#263]
I'm sure it is somewhere but I can only see that in Github page indirectly - what models are directly supported w imagainairy? They all load from hugginface by default? Could civit.ai also be supported in the same way?

**Comment by brycedrennan** [comment]
`imagine --help` should list the options but we could add a command to list them

**Comment by brycedrennan** [comment]
also viewable here https://github.com/brycedrennan/imaginAIry/blob/master/imaginairy/config.py#L32

**Comment by brycedrennan** [comment]
Added in just released `10.2.0` 

`aimg model-list`
