### ISSUE TITLE
Fast CPU support (and intel GPU support)

### ISSUE THREAD

**Issue by Astropulse** [brycedrennan/imaginAIry#265]
I saw in the todo list that CPU support was decided against because of slow performance. I found [this repo](https://github.com/bes-dev/stable_diffusion.openvino) quite a while ago and figured it might make CPU generation much more viable. It also has the added benefit of supporting Intel ARC GPUs. Not sure if it is exactly compatible due to its use of the diffusers pipeline, but it's at least interesting to take a look at.

**Comment by brycedrennan** [comment]
Looks like it would require a lot of work to integrate. Given the other features we can spend time on, I don't expect this to ever become a priority.
