### ISSUE TITLE
ControlNet pose error message

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#268]
ERROR:
Control image must be in [0, 1]

I don't understand the error message. I am using your own Indiana Pose and my own.

**Comment by brycedrennan** [comment]
I couldn't reproduce. How did you get this error?

**Comment by enzyme69** [comment]
I am using webUI automatic1111 to generate pose, save as PNG. I don't need to reprocess the image (with openpose), but not getting result. Only that error.

**Comment by enzyme69** [comment]
My command was:

imagine --control-image ./Downloads/_OpenPose_Gallery/sitting_on_sofa.png --control-mode openpose --caption-text openpose "photo of a plump panda dancing"

**Comment by enzyme69** [comment]
UPDATE: if using photo of Indiana original itself, it seems to work. While if I use the openpose colorful bone it's failling.

So maybe this become "request" if we can skip preprocessing and simply use the bone image.

**Comment by brycedrennan** [comment]
Okay I fixed the bug that allowed that incorrect error message and I added `--control-image-raw` that should let you input the pose image directly. Check out just released `10.2.0`
![015822_687609340_kdpmpp2m15_PS7 5_photo_of_a_plump_panda_dancing_ generated](https://user-images.githubusercontent.com/1217531/221383091-c7ae4d2d-0e15-4b89-bb04-b92a2444040a.jpg)
