### ISSUE TITLE
colorize, describe, controlnet in Python

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#269]
Amazing new features - love the colorize especially!

It may be obvious but...How can I use them from Python (i.e. without reloading model in between batch generation jobs)? 

Controlnet -  will it support SD2.x soon as SD1.x has quite mediocre quality for many generations.

Are there any options for Colorize (i.e. tint/ more color, less color)?

**Comment by bluusun** [comment]
Maybe I am missing something but ControlNet generations look 'off'.

Original:
![6](https://user-images.githubusercontent.com/65051271/221276795-839d7d55-2458-4397-b3b0-fd213b3b30ef.jpg)

imagine --control-image 6.jpg --control-mode depth  "a modern bathroom" --width 1000

This was produced:
![1](https://user-images.githubusercontent.com/65051271/221277897-04c22178-6171-4b2c-9885-c5f21974a87e.jpg)

**Comment by brycedrennan** [comment]
No idea whether controlnet will support 2.x.  Probably something that makes it obsolete will come out before it does :-)

**Comment by brycedrennan** [comment]
Colorize doesn't have options and doesn't work that well either yet.

**Comment by brycedrennan** [comment]
What looks off in the controlnet pictures?
