### ISSUE TITLE
InstructPix2Pix Larger images?

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#270]
Is there a way to use larger images for these compilations (or save as video)?

edit E.jpg -p "make it sunrise to sunset"  --prompt-strength 15  --steps 30 --arg-schedule prompt-strength[1:15:1] --compilation-anim gif --mask-prompt "face" --mask-mode keep - w 1200 --upscale

1200 width is acknowledged in output but ignored otherwise.

Results:

- produces a number of images in generated (760x512)
- produces a number of great images in upscaled (3040x2048)
- a (very) low res compilation

**Comment by brycedrennan** [comment]
looks like you have typo'd the width parameter. should be `-w` not `- w`

**Comment by bluusun** [comment]
Same result with the correct -w (was just a typo when copying), larger images are ignored (not used for gif)

**Comment by brycedrennan** [comment]
yes upscaled is not used in gifs.  perhaps you need to set the height as well since it's set to 512 otherwise
