### ISSUE TITLE
Controlnet Documentation?

### ISSUE THREAD

**Issue by jonathangoorin** [brycedrennan/imaginAIry#280]
Thanks for the great work!
Excited it was integrated.
How to use it?

**Comment by brycedrennan** [comment]
Guess I need to make the documentation more obvious. You click on each header to see the command:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/1217531/222307955-eb53e4ab-4938-40aa-a9e2-15329120b480.png">

**Comment by jonathangoorin** [comment]
@brycedrennan Thanks!
