### ISSUE TITLE
Ridiculous file sizes

### ISSUE THREAD

**Issue by borzecki** [brycedrennan/imaginAIry#281]
Is this a joke? I asked for an image of "dog skiing" and it started downloading 4.27G of data. Was expecting a funny jpeg, not a full HD episode of Sherlock.

Also:
<code>Generating 🖼  1/1: "dog skiing" 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art,"
</code>
<img src="https://media4.giphy.com/media/4cQSQYz0a9x9S/giphy.gif"/>

**Comment by brycedrennan** [comment]
ImaginAIry only generate the finest high-quality images and thus requires what would normally be considered a large amount of disk space.  At 4.27gb per image and a modern 1 tb hard drive you should be able to generate at least 200 images before needing to purchase a new hard drive.

**Comment by bluusun** [comment]
> Is this a joke? I asked for an image of "dog skiing" and it started downloading 4.27G of data. Was expecting a funny jpeg, not a full HD episode of Sherlock.
> 
> Also: `Generating 🖼 1/1: "dog skiing" 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," ` ![](https://camo.githubusercontent.com/7ecd1b68ba8c615946194d96a624590fe2aa00f47710eb18736d3c2b0c323766/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3463515351597a3061397839532f67697068792e676966) [ ![68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3463515351597a3061397839532f67697068792e676966](https://camo.githubusercontent.com/7ecd1b68ba8c615946194d96a624590fe2aa00f47710eb18736d3c2b0c323766/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3463515351597a3061397839532f67697068792e676966) ](https://camo.githubusercontent.com/7ecd1b68ba8c615946194d96a624590fe2aa00f47710eb18736d3c2b0c323766/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3463515351597a3061397839532f67697068792e676966) [ ](https://camo.githubusercontent.com/7ecd1b68ba8c615946194d96a624590fe2aa00f47710eb18736d3c2b0c323766/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f3463515351597a3061397839532f67697068792e676966)

LOL - quality contribution :0

**Comment by johnblommers** [comment]
So the 4.27 GB download would be a one-time occurrence. I've used Imaginairy awhile  now and at first it did a big download. But now   `imagine "dog skiing" downloaded nothing. It went straight into the 15-stage processing. Result:

![000010_77887686_kdpmpp2m15_PS7 5_dog_skiing_ generated](https://user-images.githubusercontent.com/8484427/223027250-bcf46210-e429-46f5-851e-3265014ef13e.jpg)

**Comment by borzecki** [comment]
thanks for clarification 👍

**Comment by brycedrennan** [comment]
The "todo" here is to add some message in the terminal explaining why the large downloads are happening.
