### ISSUE TITLE
Aesthetic Gradients

### ISSUE THREAD

**Issue by C00reNUT** [brycedrennan/imaginAIry#283]
Hello,

thank you for this fantastic way to use stable diffusion.  

Would it be possible to implement this feature? 

https://github.com/vicgalle/stable-diffusion-aesthetic-gradients

It provides nice improvement in aesthetics with minimal effort on user side.

**Comment by brycedrennan** [comment]
This is probably no longer worth implementing compared to Self-Attention Guidance, Controlnets, and Loras, which should be able to do the same thing.
