### ISSUE TITLE
Producing black images when try loading in a new model and use Controlnet HED

### ISSUE THREAD

**Issue by tg-synth** [brycedrennan/imaginAIry#284]
I am trying to create images using --model https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/resolve/main/dreamlike-photoreal-2.0.safetensors. It works perfectly when used in isolation, but when I try to use it with ControlNet I get black output images. ControlNet also works perfectly when it is used with the default SD model. I would love to know if there is a way I can get this to work.

**Comment by cinemapara** [comment]
I can confirm this bug, both hed and canny dont work when loading custom ckpts. With default ckpt everything is fine.

**Comment by cinemapara** [comment]
Hello @brycedrennan it could be a diffusers version mismatch.
Maybe that’s helpful

**Comment by brycedrennan** [comment]
Fixed in just released 12.0.0
