### ISSUE TITLE
ReImagine

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#286]
This looks exciting!

https://twitter.com/StabilityAI/status/1636719337024241664

Also maybe you wanna take on text models next - they're are here :)

https://github.com/tloen/alpaca-lora

**Comment by bluusun** [comment]
Ha! Can't deduct what it does yet...Also is Midjourney v5 now part of imgainAIry?

**Comment by brycedrennan** [comment]
I haven't played with midjourney but my understanding is that it only runs on their servers so can't be part of imaginairy.

**Comment by bluusun** [comment]
Oh so it isn't OpenJourney compatible?

**Comment by brycedrennan** [comment]
OpenJourney is a model someone trained to mimic midjourney. I dont think they've done the same for midjourney v5.
