### ISSUE TITLE
Colab -> ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub'

### ISSUE THREAD

**Issue by cinemapara** [brycedrennan/imaginAIry#289]
Hello @brycedrennan 
unfortunately i get the following error using the [collab](url). Maybe you have some ideas ? Best, CinemaParadiso

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/59502516/226141571-08f0a57f-8026-4916-a07a-596e8c09cc42.png">

**Comment by brycedrennan** [comment]
Hmm. I supposedly just released a fix for this less than an hour ago... let me double check things

**Comment by brycedrennan** [comment]
Oh I see the colab was pinned to 10.  Fixing now.

**Comment by brycedrennan** [comment]
Fixed.

**Comment by cinemapara** [comment]
@brycedrennan perfect. Works now. thanks for your quick help. Best, cinemaParadiso
