### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by h4rk8s** [brycedrennan/imaginAIry#29]
`
Device 0 [NVIDIA GeForce GTX 1080] PCIe GEN 3@16x RX: 25.00 MB/s TX: 6.000 MB/s
GPU 1898MHz MEM 4513MHz TEMP  72°C FAN  60% POW 189 / 200 W
`

miniforge3's ldm env, install from InvokeVI(lstein/stable-diffusion) Ubuntu .yml

Do 60 image generation at a time, args following:

`
imagine "xxxxxxx " \
        --repeats 60 \
        --steps 50 \
        --prompt-strength 7.5 \
        --sampler-type k_lms \
        --width 512 \
        --height 512 \
        --fix-faces \
        --upscale
`

It runs smoothly at first, very fast, producing a new image in about 20 seconds (For my GPU card), but after a while (usually a few minutes or so), it starts reporting errors. It looks like every iteration there are hundreds of megabytes of VRAM that are not freed up.

`
RuntimeError: CUDA out of memory. Tried to allocate 534.00 MiB (GPU 0; 7.93 GiB total capacity; 6.19 GiB already allocated; 528.81 MiB free; 6.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

I've tried the following , it maybe work.(We went from a dozen iterations to 30+)

`
+ imaginairy/utils.py step(1)

def clean_memory():
    if get_device() == 'cuda':
        gc.collect()
        torch.cuda.empty_cache()

+ imaginairy/schema.py step(2)

 ImaginePrompt.__init__()
 ...
    self.tile_mode = tile_mode
    clean_memory()

+ imaginairy/enhancers/upscale_realesrgan.py step(3)
 L37
 clean_memory()    
`
I think it's the memory fragmentation.

**Comment by brycedrennan** [comment]
Thanks for the report. I've also noticed there is some sort of memory leak. Let me know if your solution works!

**Comment by h4rk8s** [comment]
> Thanks for the report. I've also noticed there is some sort of memory leak. Let me know if your solution works!

I'm sorry that I wasn't able to solve the problem completely at this moment. I collecting the torch.cuda.memory_allocated() generated each time,I think the problem may be this pipelined image enhancement,The problem is upscale, to be exact. so check it out tonight.

# imagine with  --fix-faces \
        --upscale
repeat.1
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.51G

repeat.2
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.72G (leak 200MB)❌

repeat.3
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.92G (leak 200MB)❌


# imagine without --fix-faces \
        --upscale
repeat.1
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.17G

repeat.2
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.17G (leak 0MB)✅

repeat.3
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.17G (leak 0MB)✅

# imagine without --upscale
repeat.1
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.27G (leak 112MB) ❌

repeat.2
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.38G (leak 112MB) ❌

repeat.3
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.49G (leak 112MB) ❌

# imagine without --fix-faces
repeat.1
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.29G (leak 0MB)✅

repeat.2
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.29G (leak 0MB)✅

repeat.3
>>   Max VRAM used for this generation: 4.29G. Current VRAM utilization:2.29G (leak 0MB)✅

**Comment by brycedrennan** [comment]
awesome thank you.  I'd love to know how you output those memory stats as well. we can add a leak detector in the future

**Comment by h4rk8s** [comment]
> awesome thank you. I'd love to know how you output those memory stats as well. we can add a leak detector in the future

I see you write "Noisy logs are gone (which was surprisingly hard to accomplish)" in the description of the front page, so no unauthorized addition to the output spoils the beauty, :) I do this locally 👇

![Snapshot 2022-09-28 at 00 05 22@2x](https://user-images.githubusercontent.com/63350517/192578091-44bf941a-ab97-48cf-b76d-5c1868f680c8.png)

```python
                print(
                    f'>>   Max VRAM used for this generation:',
                    '%4.2fG.' % (torch.cuda.max_memory_allocated() / 1e9),
                    'Current VRAM utilization:'
                    '%4.2fG' % (torch.cuda.memory_allocated() / 1e9),
                )
```
