### ISSUE TITLE
How to Combine InstructPix2Pix and prompt-based masking?

### ISSUE THREAD

**Issue by cinemapara** [brycedrennan/imaginAIry#290]
Hello @brycedrennan -> I have question regarding the documentation. In the docs it's written "For extra control you can combine with prompt-based masking."

It would be great to haven a code example on how to combine those 2 techniques for example to first prompt-mask using mode:Keep and then edit the masked part with pix2pix

**Comment by brycedrennan** [comment]
here would be an example:
```bash
aimg edit https://i0.wp.com/gustavomirabalcastro.online/wp-content/uploads/2018/10/Marengo.jpg?resize=768%2C616&ssl=1 -p "replace the horse with a tiger" --prompt-strength 8 -r 10 --mask-mode replace --mask-prompt "horse OR animal OR saddle OR carpet" --steps 30
```
