### ISSUE TITLE
got an unexpected keyword argument 'prompt_library_path'

### ISSUE THREAD

**Issue by vbmark** [brycedrennan/imaginAIry#291]
Getting "got an unexpected keyword argument 'prompt_library_path'" when doing this:

```python
prompts = [ImaginePrompt(p, negative_prompt=n, prompt_library_path="./prompts")]
```

What am I doing wrong?

**Comment by brycedrennan** [comment]
yeah this isn't documented. an ImaginePrompt doesn't do any sort of prompt expansion. It expects a static prompt.  

This is probably what you're looking for though:

```python
from imaginairy.enhancers.prompt_expansion import expand_prompts

my_prompt = "a giant {_animal_}"

expanded_prompts = expand_prompts(n=10, prompt_text=my_prompt, prompt_library_paths=["./prompts"])
```
