### ISSUE TITLE
Feature request: Choose GPU id

### ISSUE THREAD

**Issue by killian31** [brycedrennan/imaginAIry#292]
Hi, thank you for your amazing work. I have several GPUs, and I'd like to have the possibility to choose which one to use when running your script. For example adding `--gpuid 2` if I want to use my gpu 2. 
Thanks!

**Comment by brycedrennan** [comment]
I've never tried it with imaginairy but I suspect you can just use the `CUDA_VISIBLE_DEVICES` environment variable.

```
CUDA_VISIBLE_DEVICES=2, aimg imagine "a beautiful sunset"
```
the comma may or may not be necessary

**Comment by killian31** [comment]
It works, thank you.
