### ISSUE TITLE
pip install imaginairy does not put binary somewhere on PATH

### ISSUE THREAD

**Issue by cartland** [brycedrennan/imaginAIry#293]
The instructions suggest that `pip install imaginary` will create a binary called `imagine`.

```bash
# on macOS, make sure rust is installed first
>> pip install imaginairy
>> imagine "a scenic landscape" "a photo of a dog" "photo of a fruit bowl" "portrait photo of a freckled woman" "a bluejay"
```

When I enter `imagine` to the shell prompt, the binary cannot be found.
```
zsh: command not found: imagine
```

I think I need the binary location so I can add it to my path. Can the documentation be updated with any additional information needed to make this run on MacOS?

Dependency versions:
* Python 3.10.10
* pip 23.0.1 
* rustc 1.68.1 (8460ca823 2023-03-20) (built from a source tarball)

**Comment by michalbrz** [comment]
I had the same issue and it's a problem with PATH not with the library, this should fix it: https://stackoverflow.com/a/62151306/2707179

**Comment by cartland** [comment]
I found the location of the binary. I am using `pyenv` and ZSH on MacOS so the packages are installed in a different place.

I can run the binary after adding added this line to `~/.zshrc`:
```bash
export PATH="$PATH:$HOME/.pyenv/versions/3.10.10/bin"
```

Here is my install flow with Homebrew:
```bash
>> brew install pyenv
>> pyenv install 3.10.10
>> pyenv global 3.10.10
>> pip install imaginairy
>> pip show imaginairy
Name: imaginAIry
Version: 5.0.1
Summary: AI imagined images. Pythonic generation of stable diffusion images.
Home-page: UNKNOWN
Author: Bryce Drennan
Author-email: 
License: UNKNOWN
Location: /Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages
Requires: click, click-shell, diffusers, einops, fairscale, ftfy, gfpgan, imageio, kornia, numpy, omegaconf, Pillow, protobuf, psutil, pytorch-lightning, realesrgan, timm, torch, torchdiffeq, torchmetrics, torchvision, tqdm, transformers
Required-by: 
```

I browsed around the folders to look for the `bin` directory and I found it here:
```bash
/Users/cartland/.pyenv/versions/3.10.10/bin
```

Thanks for the tip about `python3 -m site --user-base` but it doesn't work for my environment.
```bash
>> python -m site --user-base
/Users/cartland/.local
```

**Comment by brycedrennan** [comment]
Glad you were able to work that out. I also use pyenv and zsh. I suspect your pyenv installation isn't quite finished.  

on the [zsh github page](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv) it suggests modifying .zshrc like this:

```bash
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(pyenv init -)"' >> ~/.zshrc
```

I'd expect you to not need to manually add specific versions of python to the PATH after that

**Comment by cartland** [comment]
Thanks @brycedrennan that was the problem with my installation. Appreciate the tip!
