### ISSUE TITLE
Failed to load image Python extension - full error below

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#295]
I kept getting this crashing error when running the aimg demo:

```
(venv) jimmygunawan@192-168-1-100 ~ % aimg edit-demo /Users/jimmygunawan/stable-diffusion-webui/outputs/img2img-images/2023-03-29/00069-1339136265\ Medium.jpg 
/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: <06D2C3BD-26E5-3AB9-A866-63839BE393A7> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <44B645FB-F027-3EE5-86D7-DBF8E2FC6264> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/bin/aimg", line 6, in <module>
    imaginairy.cli.main.aimg()
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/imaginairy/cli/edit_demo.py", line 37, in edit_demo_cmd
    create_surprise_me_images(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/imaginairy/surprise_me.py", line 184, in create_surprise_me_images
    prompts = surprise_me_prompts(img, person=person, width=width, height=height)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/imaginairy/surprise_me.py", line 136, in surprise_me_prompts
    person = bool(detect_faces(img))
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/imaginairy/enhancers/facecrop.py", line 18, in detect_faces
    face_helper.get_face_landmarks_5(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 139, in get_face_landmarks_5
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/facexlib/detection/retinaface.py", line 227, in detect_faces
    keep = py_cpu_nms(bounding_boxes, nms_threshold)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/facexlib/detection/retinaface_utils.py", line 41, in py_cpu_nms
    keep = torchvision.ops.nms(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/ops/boxes.py", line 40, in nms
    _assert_has_ops()
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/extension.py", line 33, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

**Comment by brycedrennan** [comment]
What version of torch and torchvision are installed?

**Comment by enzyme69** [comment]
Not sure if this is correct:

```
Python 3.10.10 (main, Feb 16 2023, 02:49:39) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
print(torch.__version__)
>>> print(torch.__version__)
1.13.1
>>> import torchvision
/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: <06D2C3BD-26E5-3AB9-A866-63839BE393A7> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <44B645FB-F027-3EE5-86D7-DBF8E2FC6264> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
>>> 
```

**Comment by enzyme69** [comment]
(venv) (base) jimmygunawan@192-168-1-100 ~ % pip list | grep torch
open-clip-torch         2.7.0
pytorch-lightning       1.9.4
torch                   2.0.0
torchaudio              2.0.1
torchdiffeq             0.2.3
torchmetrics            0.11.1
torchsde                0.2.5
torchvision             0.13.1

**Comment by enzyme69** [comment]
I did install and uninstall, downgrading from 2.0.0 into 1.13.1 again...

🤖🧠> system-info
imaginairy_version:            11.1.0
imaginairy_path:               /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/imaginairy
python_version:                3.10.10
python_installation_path:      /Users/jimmygunawan/stable-diffusion-webui/venv/bin/python3.10
device:                        mps:0
torch_version:                 1.13.1
platform:                      darwin
hardware_description:          macOS-13.3-arm64-arm-64bit
ram_gb:                        32.0
graphics_card:                 Apple MPS

maybe fixed? but I still get the weird error 
![001115_951288451_kdpmpp2m15_PS7 5_a_sculpture_in_a_forest_ generated](https://user-images.githubusercontent.com/3952687/229066602-9f554196-a619-41c4-b083-fe4440a1a32d.jpg)


🤖🧠> imagine "a sculpture in a forest"
/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: <06D2C3BD-26E5-3AB9-A866-63839BE393A7> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <44B645FB-F027-3EE5-86D7-DBF8E2FC6264> /Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Generating 🖼  1/1: "a sculpture in a forest" 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," seed:951288451 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m init-image-strength:0.2 model:SD-1.5
Loading model /Users/jimmygunawan/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/889b629140e71758e1e0006e355c331a5744b4bf/v1-5-pruned-emaonly.ckpt onto mps:0 backend...
100%|████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:31<00:00,  2.28s/it]
    Image Generated. Timings: conditioning:2.31s sampling:32.43s decoding:1.86s safety-filter:3.39s total:40.09s
    [generated] saved to: ./outputs/generated/001115_951288451_kdpmpp2m15_PS7.5_a_sculpture_in_a_forest_[generated].jpg

**Comment by brycedrennan** [comment]
yeah that is strange. especially since it makes an image. I suspect you have the wrong version of torchvision installed. It needs to match: the version of torch you have, your OS, your python version. I'd suggest reinstalling torchvision. If that doesn't work maybe look up which version is compatible with torch 1.13.1
