### ISSUE TITLE
Aesthetic controlnet

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [brycedrennan/imaginAIry#297]
I am wondering how complex it is to integrate [Aesthetic controlnet](https://huggingface.co/krea/aesthetic-controlnet). I am happy to work on it if it doesn't require a lot of changes.

**Comment by brycedrennan** [comment]
Looks like I'd have to integrate controlnet for 2.1 first. I can't speak to how much work that is but I welcome contributions.
