### ISSUE TITLE
UnboundLocalError: local variable 'init_image_t' referenced before assignment

### ISSUE THREAD

**Issue by Explosion-Scratch** [brycedrennan/imaginAIry#299]
Every time I try to run something like `edit --prompt "make it summer" wallpaper.png` it gives this error:
```
Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Generating 🖼  1/1: "make it summer" 512x512px negative-prompt:"" seed:33652051 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m init-image-strength:1.0 model:edit
UnboundLocalError: local variable 'init_image_t' referenced before assignment
```
Not sure why it says 0 input images either

**Comment by brycedrennan** [comment]
Are you on the latest version? What is the output of `aimg system-info`?
I've seen this bug but thought I had fixed it.

**Comment by Explosion-Scratch** [comment]
```
imaginairy_version:            11.1.0
imaginairy_path:               /Users/tjs/mambaforge/lib/python3.10/site-packages/imaginairy
python_version:                3.10.8
python_installation_path:      /Users/tjs/mambaforge/bin/python3.10
device:                        mps:0
torch_version:                 1.13.1
platform:                      darwin
hardware_description:          macOS-13.3-arm64-arm-64bit
ram_gb:                        8.0
graphics_card:                 Apple MPS
```

**Comment by dirk-fr** [comment]
Same issue here.
`imaginairy_version:            11.1.0
imaginairy_path:               /opt/miniconda3/lib/python3.9/site-packages/imaginairy
python_version:                3.9.12
python_installation_path:      /opt/miniconda3/bin/python
device:                        mps:0
torch_version:                 1.13.1
platform:                      darwin
hardware_description:          macOS-13.1-arm64-arm-64bit
ram_gb:                        24.0
graphics_card:                 Apple MPS`

**Comment by dirk-fr** [comment]
Same issue here:
imaginairy_version:                  11.1.0
imaginairy_path:                       /opt/miniconda3/lib/python3.9/site-packages/imaginairy
python_version:                       3.9.12
python_installation_path:       /opt/miniconda3/bin/python
device:                                      mps:0
torch_version:                          1.13.1
platform:                                   darwin
hardware_description:            macOS-13.1-arm64-arm-64bit
ram_gb:                                    24.0
graphics_card:                         Apple MPS

**Comment by dirk-fr** [comment]
If it helps:
I also had the "0 input images" issue -- changed the input file-name to something simple ("cyborg.jpg") and provided the input image filename including full path. That seems to work.
