### ISSUE TITLE
Problems generating with --init-image

### ISSUE THREAD

**Issue by aengusl** [brycedrennan/imaginAIry#3]
Hey!

Thank you so much for this resource, it's awesome!

I've come across an issue when i try to generate using the img2img functionality. I ran the command

imagine "painting of a dog surfing" --init-image "outputs/000001_528675053_plms40_PS7.5_a_dog_with_sunglasses_surfing_a_wave.jpg"

and I got this error

AttributeError: 'PLMSSampler' object has no attribute 'stochastic_encode'

I kept getting this error after also trying to use a seed, and changing number of steps.

**Comment by wseagar** [comment]
Hi @aengusl.

For the moment please use the ddim sampler with init-image as there are some bugs with other samplers + init image right now.

try

`imagine "painting of a dog surfing" --sampler-type "ddim" --init-image "outputs/000001_528675053_plms40_PS7.5_a_dog_with_sunglasses_surfing_a_wave.jpg"`

**Comment by brycedrennan** [comment]
whoops, it was supposed to autoselect ddim if you choose provide init-image. will fix.

**Comment by brycedrennan** [comment]
fixed now in v 1.1.4. thanks for reporting

**Comment by aengusl** [comment]
cheers!
