### ISSUE TITLE
Wish there was a feature to generate an intermediate image every 5 steps or so

### ISSUE THREAD

**Issue by slashdottir** [brycedrennan/imaginAIry#304]
Just to show how the image rezzes up.

Trying to pick through the code myself to understand it, but haven't quite figured out where and when to put the logic.

Really love this program. Thank you

**Comment by brycedrennan** [comment]
I think there is a feature. if you add `--gif` to the imagine command. does that do what you want?

```
>> imagine --gif "a flower"
```
https://raw.githubusercontent.com/brycedrennan/imaginAIry/master/assets/009719_942389026_kdpmpp2m15_PS7.5_a_flower.gif

**Comment by slashdottir** [comment]
I will try it, thanks for responding!
