### ISSUE TITLE
run a shell command in PHP 

### ISSUE THREAD

**Issue by Cristobalpixel** [brycedrennan/imaginAIry#305]
I want to run a command in PHP to generate an image : 
```php
$make_test      = system("/usr/local/bin/aimg  version ");
$make_image  = system("/usr/local/bin/imagine  --outdir ../outputs 'a orange bird'  ");
```

Results in : 
```
11.1.0 
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory. 
```

I can't generate outputs... Empty folder.
Any suggestions ?

**Comment by Cristobalpixel** [comment]
PHP is running from XAMPP:
error-log: 
Original error was: dlopen(/Library/Python/3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): tried: '/Library/Python/3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by Cristobalpixel** [comment]
SOLVED !
This works > $make_magic  = system("arch -arm64 /usr/local/bin/imagine  --outdir ./output_site/outputs 'a orange bird'  ");
'arch -arm64 ' <-- force to use arm64

No i can make my own web UI. (local)

**Comment by brycedrennan** [comment]
Glad you got it working. I'm pretty confused as to why it wouldn't have been working. Must be something about running PHP on an M1.

I'd point out that your current approach means that you'll be reloading the models from disk for every command invocation. This could be pretty slow.  Running a python server would probably be easier and faster.

Also you'll have to figure out how to handle or prevent concurrent image generations.
