### ISSUE TITLE
--model-config-path    doesn't work

### ISSUE THREAD

**Issue by Cristobalpixel** [brycedrennan/imaginAIry#308]
i need to load a config with a .ckpt : 

--model-config-path  ./checkpoints/graphicArt_graphicArtBeta11.yaml    <  error : FileNotFoundError: [Errno 2] No such file or directory: '/Library/Python/3.8/site-packages/imaginairy/graphicArt_graphicArtBeta11.yaml'
It's a path problem for the config file.

--model-weights-path ./checkpoints/graphicArt_graphicArtBeta11.safetensors   < this path works for my checkpoints

**Comment by brycedrennan** [comment]
Fixed in just released 12.0.0
