### ISSUE TITLE
Add option for outputting Quadratic or images in a grid format -g

### ISSUE THREAD

**Issue by CptPlastic** [brycedrennan/imaginAIry#311]
Awesome work! It would be nice to have a way to output 4 images as a grid.

**Comment by CptPlastic** [comment]
Ive tried -tile and its not tiling the output even when generating -r4 or any amount. Im not sure if this is a bug or by design.

**Comment by brycedrennan** [comment]
I don't plan on adding the grid output feature -  sorry! 😄 

`--tile` makes the generated images such that if you repeat them they seamlessly blend together.  easiest way to understand is to set one of them as your desktop background in "tile" mode.

**Comment by CptPlastic** [comment]
I worked around this by adding an attachment bit of code to my bot so it outputs just like a grid. It also names the files properly so the user can do stuff to them. SEEEE
![image](https://user-images.githubusercontent.com/1010444/236368839-02d50163-f864-4adb-b047-9d9656a50acd.png)

**Comment by brycedrennan** [comment]
nice - well done
