### ISSUE TITLE
upscale only from python?

### ISSUE THREAD

**Issue by maschinenzeitmaschine** [brycedrennan/imaginAIry#312]
i want to just upscale an existing image, like this:
```
# upscale an existing image
>> aimg upscale my-image.jpg

```
but how would i use this from normal python? is there any example somewhere?
also, i'm wondering: are there different models or modes for this? i see esrgan, but also something called "riverwing" in the code but i'm too dumb to make sense out of it…

**Comment by brycedrennan** [comment]
I'll add this example to the docs:


```python
from imaginairy.enhancers.upscale_realesrgan import upscale_image
from PIL import Image
img = Image.open("my-image.jpg")
big_img = upscale_image(i)
```

This is what the command line tool uses. Yes there are other upscalers in the code. I've been toying with them but I haven't been satisfied with their performance yet.
