### ISSUE TITLE
can not import ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (C:\Users\koorosh\aiproject\aiproject\Lib\site-packages\transformers\utils\hub.py)

### ISSUE THREAD

**Issue by keloniton** [brycedrennan/imaginAIry#322]
Hi, 
I spent more than 5 hours trying to use this package. 
Finally, i get error 
ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (C:\Users\koorosh\aiproject\aiproject\Lib\site-packages\transformers\utils\hub.py)

i tried to reinstall pip install --upgrade --force-reinstall huggingface_hub as i search hffolder is a part of this package. It did not solve the problem. I am using windows os.

this is my aimg system-info :
imaginairy_version:            11.0.0
imaginairy_path:               C:\Users\koorosh\aiproject\aiproject\Lib\site-packages\imaginairy
python_version:                3.11.3
python_installation_path:      C:\Users\koorosh\aiproject\aiproject\Scripts\python.exe
device:                        cpu
torch_version:                 2.0.1+cpu
platform:                      win32
hardware_description:          Windows-10-10.0.19044-SP0
ram_gb:                        7.88

I also tried to update: pip install imaginairy==11.1.0
It arises the error: ERROR: Could not find a version that satisfies the requirement torch<2.0.0,>=1.13.1 (from imaginairy) (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch<2.0.0,>=1.13.1

I also removed all of the installed packages by pip and also i cleaned all of the cashed files by pip. then i tried to install :
pip install imaginairy==11.1.0
But I still get error:
ERROR: Could not find a version that satisfies the requirement torch<2.0.0,>=1.13.1 (from imaginairy) (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch<2.0.0,>=1.13.1
I am really confused. What is wrong. Why cant version 11.1.0 be installed?

 I appreciate any help.

**Comment by keloniton** [comment]
this is my aimg system-info :
imaginairy_version:            11.0.0
imaginairy_path:               C:\Users\koorosh\aiproject\aiproject\Lib\site-packages\imaginairy
python_version:                3.11.3
python_installation_path:      C:\Users\koorosh\aiproject\aiproject\Scripts\python.exe
device:                        cpu
torch_version:                 2.0.1+cpu
platform:                      win32
hardware_description:          Windows-10-10.0.19044-SP0
ram_gb:                        7.88

**Comment by keloniton** [comment]
I also removed all of the installed packages by pip and also i cleaned all of the cashed files by pip. then i tried to install :
pip install imaginairy==11.1.0
But I still get error:
ERROR: Could not find a version that satisfies the requirement torch<2.0.0,>=1.13.1 (from imaginairy) (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch<2.0.0,>=1.13.1
I am really confused. What is wrong. Why cant version 11.1.0 be installed?

**Comment by brycedrennan** [comment]
imaginairy doesn't yet support torch 2.0. I think that's the problem you're facing.

**Comment by keloniton** [comment]
I have a question. May i have your email to send what i want to do with this package, and you give me your idea about settings, Thanks.

**Comment by brycedrennan** [comment]
I'm not really keen to give out my email address publicly but it can be found online in various places if you look.  Happy to just respond here as well.

**Comment by keloniton** [comment]
Alright, I have image of two sneaker shoes, I want AI to imagine a girl who is wearing black jeans wear them too,  I want the zoom of camera on her legs and shoes as a model , i need the shoes in the result image to be exactly as the original image of shoes. so i dedicate more weight to shoes like 1. I will be out painting i think. I tried couple of commands but no success, I 'll appreciate if you give me your idea.  

sample image:
https://i.postimg.cc/ZK1kXrJ5/out.jpg

**Comment by keloniton** [comment]
Any idea? I'll appreciate any help! thanks.

**Comment by brycedrennan** [comment]
This should get you started. I think you could get more advanced by generating the legs separately, placing the shoes on top and then inpainting the area between the shoes and legs.

imagine --init-image https://i.postimg.cc/ZK1kXrJ5/out.jpg --mask-prompt "NOT shoes" "a woman wearing black jeans and shoes" --mask-mode replace --outpaint up400,left200,right200 -r 20 -w 768 -h 768 --upscale --steps 30

![021318_935409838_kdpmpp2m30_PS7 5_img2img-0 0_a_woman_wearing_black_jeans_and_shoes_ modified_original](https://github.com/brycedrennan/imaginAIry/assets/1217531/e3d087a9-4ddd-4ae6-a27d-c77516060ef7)

![021334_337232666_kdpmpp2m30_PS7 5_img2img-0 0_a_woman_wearing_black_jeans_and_shoes_ modified_original](https://github.com/brycedrennan/imaginAIry/assets/1217531/ff20093b-3c2a-4091-a658-a59828bb3cba)
