### ISSUE TITLE
ModuleNotFoundError: No module named '_hub'

### ISSUE THREAD

**Issue by nhuhoan** [brycedrennan/imaginAIry#323]
When I run the command : imagine "a scenic landscape" 

then there is an error message like this : ModuleNotFoundError: No module named '_hub'

please let me know how to fix this issue

**Comment by phagenlocher** [comment]
A quick but temporary solution is to fix the import locally. In my case, the file `/usr/local/lib/python3.10/dist-packages/timm/models/hub.py` had the import statement `from _hub import *` which I changed to `from ._hub import *`. After that, it worked fine.

**Comment by brycedrennan** [comment]
[This was a bug in `timm`. ](https://github.com/huggingface/pytorch-image-models/pull/1804). They haven't released the fix yet. Meanwhile I've updated imaginairy's dependencies to exclude the broken versions.  

Fixed in just released 12.0.3
