### ISSUE TITLE
Update to Real-ESRGAN v0.3.0

### ISSUE THREAD

**Issue by adammenges** [brycedrennan/imaginAIry#326]
FYI there's Real-ESRGAN v0.3.0 (vs v0.1.0 in the code now), tho not sure how much it matters.

**Comment by brycedrennan** [comment]
I don't see new weights though. There are some new tiny weights but I assume they perform worse than what we're using right now: 
> They are very tiny models for general scenes, and they may more robust. But as they are tiny models, their performance may be limited
https://github.com/xinntao/Real-ESRGAN/releases
