### ISSUE TITLE
import other models instead of built-in models

### ISSUE THREAD

**Issue by hclvclhopccw** [brycedrennan/imaginAIry#328]
Hi, may I know whether I can import other downloaded models into the library or not? Thank you very much for your help!

**Comment by brycedrennan** [comment]
Please provide more details. I don't understand the question. Do you mean custom finetunes?

**Comment by hclvclhopccw** [comment]
Actually, I want to use some checkpoint models download from https://civitai.com/ . I don't know how to import into the library.
Thanks for your reply!

**Comment by brycedrennan** [comment]
just provide the `--model` argument with the weights you want to use
