### ISSUE TITLE
Support for other models

### ISSUE THREAD

**Issue by adammenges** [brycedrennan/imaginAIry#331]
Could we get other models in here? Like: `wavymulder/wavyfusion`

Would be cool if you could give it a hugging face url, and if it's a valid model it can use, it goes for it.

**Comment by brycedrennan** [comment]
Good news for you! Already supported:
```
imagine --model https://huggingface.co/wavymulder/wavyfusion/resolve/main/wa-vy-fusion_1.0.safetensors "wa-vy style painting grim reaper" -r 4 --steps 30
```

**Comment by CptPlastic** [comment]
You can import your own models by adding it to the models.py and make sure you have the correct syntax and yaml support files as needed. I've added a custom model from huggingface before.
