### ISSUE TITLE
error when running imagine 

### ISSUE THREAD

**Issue by keloniton** [brycedrennan/imaginAIry#334]
I am using this code. 
imagine --init-image image.jpg --mask-prompt "NOT shoes" "a woman wearing black jeans and shoes" --mask-mode replace --outpaint up400,left200,right200 -r 1 -w 768 -h 768 --upscale --steps 30

I get the following error: 
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 5435817984 bytes.

It takes long time to proceed, and then it arises this error and stops.
What is my problem. I'll appreciate any help.

**Comment by brycedrennan** [comment]
what is the output of `aimg system-info`?  sounds like your machine doesn't have good enough hardware. you could try a smaller image size
