### ISSUE TITLE
StableStudio 500 error after about 10min of use

### ISSUE THREAD

**Issue by CptPlastic** [brycedrennan/imaginAIry#336]
I know this is a new feature but thought I would post this as something to take a look at.

It runs fine for a while then starts to post 500's (is there a log output that's better for the error?)

POST /api/stablestudio/generate HTTP/1.1" 500 Internal Server Error
![2023-05-22 15_53_22-graSSHopper](https://github.com/brycedrennan/imaginAIry/assets/1010444/2b3d03fe-d70d-4174-9790-59e4fafc865d)

**Comment by brycedrennan** [comment]
I wasn't able to reproduce but I agree the error messages aren't very useful. Will fix.

**Comment by brycedrennan** [comment]
Full stack trace will now be printed to console upon error in just released 13.0.1.
