### ISSUE TITLE
Support for Deepfloyd IF?

### ISSUE THREAD

**Issue by maschinenzeitmaschine** [brycedrennan/imaginAIry#337]
Just wondering, is there any plan (or rather: hope) to also support Deepfloyd_IF, or is this outside the scope of this project? Because in my tests, the results are just sooo much better in certain cases…

**Comment by maschinenzeitmaschine** [comment]
I guess it really depends on the use case: Sure one can't tweak it as one can do with Stable Diffusion, but e.g. I generate my prompts with an LLM and in this case, Deepfloyd is lightyears ahead – simply because it understands my (mediocre) prompts way better. If I may try to convince you… I'd argue enabling this kind of programmatic approach with an easy-to-use library in Python really is the core selling point of imaginAIry. And I definitely would not mind lacking fine-grained features at all... : )

**Comment by brycedrennan** [comment]
We're not planning on supporting DeepFloyd but will be adding support for SDXL.
