### ISSUE TITLE
Is there a particular reason `enhance_faces()` has to be run twice on upscaled images?

### ISSUE THREAD

**Issue by NiclasEriksen** [brycedrennan/imaginAIry#34]
```python
if prompt.fix_faces:
    logger.info("    Fixing 😊 's in 🖼  using CodeFormer...")
    img = enhance_faces(img, fidelity=0.2)
if prompt.upscale:
    logger.info("    Upscaling 🖼  using real-ESRGAN...")
    upscaled_img = upscale_image(img)
    if prompt.fix_faces:
        logger.info("    Fixing 😊 's in big 🖼  using CodeFormer...")
        upscaled_img = enhance_faces(upscaled_img, fidelity=0.8)
```

The upscaled version has significantly more "washed out" features as a consequence, with much less detail than its original scale counterpart.

Regular image with `fix_faces`:
![image](https://user-images.githubusercontent.com/6581035/193449057-4b708b8f-e50a-453f-9d4e-9de2ec52a1af.png)

Upscaled image with `fix_faces`:
![image](https://user-images.githubusercontent.com/6581035/193449081-e963d184-0dbd-4e98-a9e6-5990ca06b0d3.png)

It's particularly visible in the hair. Could it be an idea to move the upscaling to happen _before_ the face fixing to avoid this?

```python
if prompt.upscale:
    logger.info("    Upscaling 🖼  using real-ESRGAN...")
    upscaled_img = upscale_image(img)
    if prompt.fix_faces:
        logger.info("    Fixing 😊 's in big 🖼  using CodeFormer...")
        upscaled_img = enhance_faces(upscaled_img, fidelity=0.8)
elif prompt.fix_faces:
    logger.info("    Fixing 😊 's in 🖼  using CodeFormer...")
    img = enhance_faces(img, fidelity=0.2)
```

Or simply remove the enhance_faces() call for the upscaled img, or make it an optional flag?

**Comment by brycedrennan** [comment]
I hadn't noticed the washed out faces. I ran it twice so that any faces not detected in the smaller version would be picked up in the larger version.  Given what you've pointed out, seems reasonable to just run it at the lower scale until someone finds a better solution.

**Comment by brycedrennan** [comment]
I've pushed out the changes that address this in version 2.2.0
