### ISSUE TITLE
Can't find where to run in GPU Mode

### ISSUE THREAD

**Issue by YelbyTheCat** [brycedrennan/imaginAIry#346]
I'm trying to figure out where to set it to GPU mode, (windows) because I have 12 GB of vram and my friend on his has 24 GB, but its still running in cpu mode

**Comment by brycedrennan** [comment]
Probably implies you don't have CUDA setup for your graphics card or that your graphics card is not CUDA compatible at all.

**Comment by YelbyTheCat** [comment]
> 

I'm running a rtx 3080, and according to Blender, I can do CUDA rendering with it

**Comment by brycedrennan** [comment]
well run https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html must be returning false if imaginairy isn't automatically using the GPU. 🤷 Get that returning "true" and imaginairy will use the GPU
