### ISSUE TITLE
reverse prompt feature

### ISSUE THREAD

**Issue by slashdottir** [brycedrennan/imaginAIry#349]
This might be a lot to ask but it would be *so cool* if they could add in the reverse prompt feature found in this notebook

https://colab.research.google.com/github/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator.ipynb

IOW, it accepts a picture and makes a pretty good guess at a prompt keywords it could have been derived from.

please, please and thank you for this awesome program!

**Comment by PaulMest** [comment]
Looks like a BLIP implementation is already part of the CLI.
```
>> aimg describe assets/mask_examples/bowl001.jpg
a bowl full of gold bars sitting on a table
```

Does this do what you want it to do? If not, where does it fall short?

**Comment by brycedrennan** [comment]
Yeah I'd suggest using BLIP.  Last I looked at the "reverse prompt" scripts like the one you linked, they tended to give the illusion of reversing the prompt more that actually doing so.
