### ISSUE TITLE
Got a strange issue with environment

### ISSUE THREAD

**Issue by billzhao9** [brycedrennan/imaginAIry#350]
Just simple use this code 
prompts = [
    ImaginePrompt("fruit salad", tile_mode=True),
]
for result in imagine(prompts):
    result.save("my_image.jpg")

As long as I put tile_mode there, it returns 

 198 │                                                                                 │
│   199 │   def __init__(self, prompt=None, **kwargs):                                    │
│   200 │   │   # allows `prompt` to be positional                                        │
│ ❱ 201 │   │   super().__init__(prompt=prompt, **kwargs)                                 │
│   202 │                                                                                 │
│   203 │   @validator("prompt", "negative_prompt", pre=True, always=True)                │
│   204 │   def make_into_weighted_prompts(cls, v):                 

/mnt/e/AIProject/-imaginAIry/pydantic/main.py:341 in pydantic.main.BaseModel.__init__   │
│                                                                                         │
│ [Errno 2] No such file or directory: '/mnt/e/AIProject/-imaginAIry/pydantic/main.py'    

It somehow tries to load pydantic via the project folder which it's very strange
However, if I don't use the "tile_mode", it can generate image without any issues

**Comment by billzhao9** [comment]
same issue with command line.  somehow it tries to use the pydantic under the project folder. But I don't have pydantic saved under the local project folder.  I also tried to copy and paste pydantic repo under the project folder, it still pops other errors.

**Comment by brycedrennan** [comment]
I was unable to recreate this. Does the file `/mnt/e/AIProject/-imaginAIry/pydantic/main.py` exist on your system?
