### ISSUE TITLE
SDXL Support

### ISSUE THREAD

**Issue by cinemapara** [brycedrennan/imaginAIry#356]
Hello, are you planning to add support for SDXL ? Best, Andre

**Comment by brycedrennan** [comment]
I'm looking at it. Made a go a week or two ago but left with the impression it was better to wait till they had worked out some bugs. Revisiting now.

**Comment by bluusun** [comment]
Looks like Controlnet now supports SDXL:

https://huggingface.co/docs/diffusers/main/en/api/pipelines/controlnet_sdxl

**Comment by bluusun** [comment]
BTW I found SDXL a breeze to use outside imaginary. It uses much less RAM by default and the standard image generation/ controlnet use rather easy. There are some questions like guidance scale and controlnet parameters that seem quite random judging from the documentation.

**Comment by brycedrennan** [comment]
Good to hear. Where are you using it?

**Comment by bluusun** [comment]
Been using it just like Imaginairy for txt2img and img2img. What I struggled with is to finetune parameters for image similarity - seems too many options for what I can handle :)

**Comment by brycedrennan** [comment]
So you're just using the vanilla sdxl repo?

**Comment by bluusun** [comment]
Wrote just 5kB of Python. But yes it has img2img inbuilt.

 from diffusers import StableDiffusionXLPipeline
    import torch

    torch.cuda.empty_cache()

    base_model_id = "stabilityai/stable-diffusion-xl-base-1.0"

    pipe =StableDiffusionXLPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)

    pipe = pipe.to("cuda")

   num_samples = 3
    guidance_scale = 12.5
    num_inference_steps = 75

    generator = torch.Generator("cuda").manual_seed(0)


    images = pipe(
    prompt,
    negative_prompt=negative_prompt,
    num_images_per_prompt=num_samples,
    num_inference_steps=num_inference_steps,
    guidance_scale=guidance_scale,
    generator=generator
    ).images

Took Controlnet code from here: https://github.com/huggingface/diffusers/pull/4592

**Comment by brycedrennan** [comment]
Interesting. Maybe I should just integrate with diffusers

**Comment by Insaned79** [comment]
Hi. May I ask how things are going with this? Do you have any plans to implement this? I am grateful in advance

**Comment by brycedrennan** [comment]
Yes I'm integrating with the [refiners](https://github.com/finegrain-ai/refiners) library, which supports SDXL.  The SD1.5 generations now use this.

Basically the challenge is that refiners uses a different weight format so I need to write realtime conversion script. I've only gotten it done for SD15 and the controlnets so far.  Worked on it tonight, but this is just a side project so it could be a while.

**Comment by bluusun** [comment]
Also have you seen this?

https://github.com/williamyang1991/Rerender_A_Video

**Comment by brycedrennan** [comment]
Both pretty interesting. who knows when there will be time to integrate

**Comment by brycedrennan** [comment]
Added in just released 14.0.0
