### ISSUE TITLE
FEEDBACK imaginAIry to run a bit faster on M1 8GB machine?

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#36]
If I use DiffusionBee app, I can have result under 4 minutes, I wonder now if imaginAIry with it's beautiful text based Terminal command can also perform more or less in such speed?

What could be a way to run this faster?

**Comment by brycedrennan** [comment]
Are you saying it runs at the same speed as diffusionbee? or slower?

**Comment by brycedrennan** [comment]
Closing for now. Happy to re-open if I get more info.
