### ISSUE TITLE
Problem with using mask to keep an object in image generation

### ISSUE THREAD

**Issue by keloniton** [brycedrennan/imaginAIry#361]
Hello, I am using the following command to use this package to generate some product images. I use the following prompt to keep my image and put it in various locations. But as you see, there is another image under my main image. It is bigger and lower parts of this product is shown under my product. I appreciate any help @brycedrennan  
prompt: 
`
imagine --init-image 3.jpg --mask-prompt "shoes" --mask-mode keep "Product photography, shoes product, lying on the water surface, with flowers, stone on sparkling water, natural lighting, nature photorealistic photography, dreamy tones, focus on product, center composition, high resolution"  -r 1 -w 500 -h 500 --upscale --steps 50 --prompt-strength 50 --model LI-1.0
`
![000188_74814942_kdpmpp2m50_PS50 0_img2img-0 0_Product_photography,_shoes_product,_lying_on_the_water_surface,_with_flowers,_stone_on_sparkling_water,_natural_lighting,_nature_p_ upscaled](https://github.com/brycedrennan/imaginAIry/assets/26356378/c49df1be-1285-4021-b4a9-611246ed3e87)

**Comment by keloniton** [comment]
here is main image: 
![3](https://github.com/brycedrennan/imaginAIry/assets/26356378/9f604b63-66f1-45ae-8543-98f95c5f2d3c)

**Comment by keloniton** [comment]
I will appreciate any help Mr. @brycedrennan
Let me thank you for your kindness.

**Comment by ahmed-mohamed-sn** [comment]
@keloniton I can see that you are using a custom model but I am curious if you tried using a lower prompt strength (5-10).

**Comment by keloniton** [comment]
@ahmed-mohamed-sn I tested with strength of 6. No thing changed, I think the problem should be some thing different.

**Comment by ahmed-mohamed-sn** [comment]
did you try using the mask modifiers to expand the mask area and/or strength? (e.g. mask prompt: shoes {+5}{*3})

<img width="803" alt="Screenshot 2023-08-11 at 14 59 33" src="https://github.com/brycedrennan/imaginAIry/assets/9744735/787b4b28-905f-49d8-a5cd-75cc492e4578">

**Comment by keloniton** [comment]
@ahmed-mohamed-sn @brycedrennan 
I used the mas modifier to decrease the mask strength and area, It did not work. I think the problem is that, Imaginary places an object (for example shoes in my example) for creating image at first, and then if we use --mask-mode keep (or replace), it will put our init_image on that (some how overlay our image on it). If the size of imaginary shoes are bigger than our shoes, some parts of it are shown. so using mask modifier will not change the result. 
![000303_612841245_kdpmpp2sa50_PS50 0_img2img-0 0_Product_photography,_children_small_shoes_product,_lying_on_the_water_surface,_with_flowers,_stone_on_sparkling_water,_natural_lig_ generated](https://github.com/brycedrennan/imaginAIry/assets/26356378/7c0bde0c-6af5-4378-a730-12d6fdcd343c)

I also tried out painting with PNG (transparent image) and white background image. It does not help. 
Transparent:
![000292_650107520_kdpmpp2sa50_PS7 5_img2img-0 0_Product_photography,_shoes_product,_lying_on_the_water_surface,_with_flowers,_stone_on_sparkling_water,_natural_lighting,_nature_p_ generated](https://github.com/brycedrennan/imaginAIry/assets/26356378/286c6e3e-06f8-47c2-94a5-ef0a4b37de0e)


White background
![000291_744046657_kdpmpp2sa50_PS7 5_img2img-0 0_Product_photography,_shoes_product,_lying_on_the_water_surface,_with_flowers,_stone_on_sparkling_water,_natural_lighting,_nature_p_ generated](https://github.com/brycedrennan/imaginAIry/assets/26356378/424018c5-696f-4ccc-8f9a-84f8c4325687)


I think there should be another way. Any idea?

**Comment by keloniton** [comment]
@brycedrennan 
Do you have any idea how to solve this problem. I will appreciate your help. Thanks.

**Comment by keloniton** [comment]
No one answers here?! 
@brycedrennan
