### ISSUE TITLE
Running in google colab returns error libtorchaudio.so: undefined symbol

### ISSUE THREAD

**Issue by jonathangoorin** [brycedrennan/imaginAIry#362]
While running in the colab (provided in the readme)
https://colab.research.google.com/drive/1rOvQNs0Cmn_yU1bKWjCOHzGVDgZkaTtO

I install and then restart the runtime - but get this error 

OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by supreme-core** [comment]
I'm having this issue as well.

**Comment by brycedrennan** [comment]
confirmed.

**Comment by brycedrennan** [comment]
Fixed
