### ISSUE TITLE
Calling all power users!

### ISSUE THREAD

**Issue by NicketUttarwar** [brycedrennan/imaginAIry#363]
Is there a Slack, Discord, or Fediverse place where I can find power users?

I'm a startup founder looking for consultants($) or advisors(shares) who can help me specifically with imaginAIry development. I'm building on a linux server with a GPU, and I have the hard tech covered, but i'm looking for someone who can help me with prompt and tool use. Hell, @brycedrennan, if you're interested I'd be more than thrilled to work with you!

Feel free to respond to this thread or if you're shy just reach out to me directly at contact.rtcltv@gmail.com

-Nicket

**Comment by brycedrennan** [comment]
@NicketUttarwar thanks for reaching out. No there isn't a discord or similar place.  I suspect there aren't enough users to make it interesting, but I might as well make one. I'll post the link here shortly.

I'm always happy to see people doing creative things with imaginairy.  I'll shoot you an email to learn more.  Sorry for the delayed response- just had a baby a few weeks ago! :-)

And i'll leave this issue open a few more weeks just in case it helps you get some contacts.

**Comment by brycedrennan** [comment]
New, empty discord server for imaginairy: https://discord.gg/FdD7ut3YjW

**Comment by brycedrennan** [comment]
I'm cleaning up the issues. You could open this as a discussion if you wish.
