### ISSUE TITLE
Pip package installation is throwing bunch of errors

### ISSUE THREAD

**Issue by supreme-core** [brycedrennan/imaginAIry#364]
Hi,

I tried Google Colab (Python3.10) and DeepNote (Python3.9) to see if I can make it run. The current version is not working, I tested a few times and unable to get it to work.

```
pip install imaginary
imagine 'a flower'
```

Is there a particular setup needed for this to work? Do you happen to have a Jupyter notebook with a simple example that is working?

**Comment by PaulMest** [comment]
You have a typo in the package name and are trying to install the wrong package... since this is an AI enhanced library, the author spells it "imaginairy". Try this instead:

```
pip install imaginairy
```

**Comment by brycedrennan** [comment]
thanks @PaulMest
