### ISSUE TITLE
Image Quality Scoring

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#365]
Can imaginary score generated images (i.e blurry/ grainy/ five arms, broken faces) somehow? Is there another github repo that can do that?

**Comment by brycedrennan** [comment]
Yes but it probably won't work as reliably as you'd like:
```python
from imaginairy.enhancers.describe_image_clip import find_img_text_similarity

image = Image.open("image.jpg")
phrases = ["blurry", "five arms", "grainy", "broken faces"]
probs = find_img_text_similarity(image, phrases)
```

**Comment by bluusun** [comment]
Thanks! That is not available via command line, right? Haven't dug into the enhancers yet...

**Comment by brycedrennan** [comment]
no its not, doesn't seem like a common enough use case to want to run at the command line.  How would you envision using that?

**Comment by bluusun** [comment]
I have not tested it yet but the idea is to discard 'failed AI' generations automatically. A bit like the NSFW filter works.

**Comment by brycedrennan** [comment]
It's an interesting idea. That's exactly how the nsfw filter works.

I haven't tried it because I expect I'd be looking for things that are already in the negative prompt so if the AI knew how to recognize them then it wouldn't have drawn them in the first place.

But would be great to know how your experiment works out.

**Comment by bluusun** [comment]
I think the idea would be to use a different model for that evaluation (if possible one that is less related). i.e. use openjourbey to evaluate stable diffusion. SDXL has a refiner that is (maybe) similar.

**Comment by brycedrennan** [comment]
Interesting idea. I should point out that image/text similarity is calculated using just the clip model.  I don't think that it'll be affected by fine tunes but I'm not 100% sure.

**Comment by bluusun** [comment]
Are there alternatives to clip like UUNet?

**Comment by brycedrennan** [comment]
Yes there are alternatives, off the top of my head there is open-clip: https://github.com/mlfoundations/open_clip
