### ISSUE TITLE
Can i use control image and masking Simultaneously

### ISSUE THREAD

**Issue by keloniton** [brycedrennan/imaginAIry#372]
Hi. Thanks for your good package. 
Is there a way to use control image and masking Simultaneously. I mean i give a controll image at first and use imagine, then the created image will be as controll image (size, shape and etc), then i use mask keep to put the same image on created image. Is there any way? Thanks.

**Comment by brycedrennan** [comment]
Yes just use the mask arguments at the same time as the controlnet arguments
