### ISSUE TITLE
Create image is very slow

### ISSUE THREAD

**Issue by xzitlou** [brycedrennan/imaginAIry#374]
Hello, I'm trying to create multiple images, but it's taking too long despite running them on GPU. I wanted to know if it's an issue with the command I'm using and if you could help me check how to optimize it or if there's something in it that you think should be removed to make it faster. I saw some examples in Colab that took between 10 to 20 seconds.

```
aimg imagine "Dog flying crossing clouds" --model openjourney-v4 --fix-faces --width 512 --height 768 --outdir "/examples/"
```

Do you think it should be faster doing it with the python library?
```
prompts = [
    ImaginePrompt(
        "Dog flying crossing clouds, 
        ...
    )
]
```

BTW, I'm using django_rq to manage all image generations to prevent burn my laptop LOL. Thanks for your help!

**Comment by brycedrennan** [comment]
Are you saying you've noticed it going slower than it used to? Or was it always slow? How long did it take? Doesn't doing multiple images make it slower?

can you paste the output of `aimg system-info`?

**Comment by xzitlou** [comment]
Hi @brycedrennan thanks for your response and for your help.
It was always slow, it takes more than a 40secs to create an image. I have 3 workers using 1 GPU/24 GB
This is the output:
```
> aimg system-info
imaginairy_version:            11.1.1
imaginairy_path:               /home/www/api/venvIMG/lib/python3.8/site-packages/imaginairy
python_version:                3.8.10
python_installation_path:      /home/www/api/venvIMG/bin/python
device:                        cuda
torch_version:                 1.13.1+cu117
platform:                      linux
hardware_description:          Linux-5.4.0-162-generic-x86_64-with-glibc2.29-Tesla P40
ram_gb:                        125.51
cuda_version:                  11.7
graphics_card:                 Tesla P40
graphics_card_memory:          25632964608
graphics_card_processor_count: 30
graphics_card_hw_version:      6.1
```

**Comment by xzitlou** [comment]
Hi @brycedrennan, does the information above give you any clues? Thanks again for your help

**Comment by brycedrennan** [comment]
I have limited experience with generating images on a queue but I would expect that three workers doesn't help much since only one worker can use the GPU at a time.  Does it go faster with only 1 worker? If not maybe its just not the fastests GPU?

**Comment by xzitlou** [comment]
Thanks @brycedrennan I will make some tests
