### ISSUE TITLE
Error: Invalid value for '--control-mode': 'details' is not one of '', 'canny', 'depth', 'normal', 'hed', 'openpose'.

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#376]
mode "Details" seems gone missing - worked until last week?

Version 10.1.1

**Comment by bluusun** [comment]
Edit is gone as well :(

**Comment by brycedrennan** [comment]
well that was lame of me. I'm working on adding a much more rigorous set of tests so this sort of thing doesnt happen again

**Comment by bluusun** [comment]
Hehe sh*t happens :) Thanks for all the great work!

**Comment by brycedrennan** [comment]
wait `Version 10.1.1` is pretty old right?

**Comment by brycedrennan** [comment]
The error `Control image must be in [0, 1]` seems like its from an old version.

**Comment by bluusun** [comment]
I can't upgrade anymore because of https://github.com/brycedrennan/imaginAIry/issues/373

**Comment by brycedrennan** [comment]
okay I'm working on #373 but I don't see anything actionable here although I didn't look very hard.  details and edit working for me.  maybe update to a specific version that predates the pydantic additions

**Comment by bluusun** [comment]
Ah makes total sense!
