### ISSUE TITLE
issues with clothing replacements using masks

### ISSUE THREAD

**Issue by ziyadm** [brycedrennan/imaginAIry#38]
I've been trying imaginary to swap clothes in photos (example mask is t-shirt), replace the mask with "yellow t shirt", but the results don't seem to work

Sometimes the mask isn't replaced at all, and sometimes it is replaced with something that doesn't match the prompt.

I've tried changing the prompt strength and init image strength, but can't seem to get what I want. Any suggestions on how I can tweak things to look like reasonable clothing replacements?

**Comment by brycedrennan** [comment]
yeah interesting. the old image seems to be leaking through somehow

**Comment by ziyadm** [comment]
Yup, lmk if there's anything I can do to help (example images/init strength/prompt multiplier) etc.

Btw the example commands for this use case could be updated (happy to send a PR but for example the prompt strength multiplier doesn't feed through, and a few other small things).

Overall awesome idea and library btw 😀

**Comment by brycedrennan** [comment]
I've released a fix for when you set init-image-strength to zero in 2.2.1

This is the example I worked with.   Expanding the mask, fixing the bug, and increasing the prompt strength seemed to work to change the shirt color.
```bash
imagine "man wearing blue t-shirt" --seed 615338918
```
```bash
imagine "solid red t-shirt being worn by a man" -r 4 --init-image outputs/generated/000079_615338918_plms40_PS7.5_man_wearing_blue_t-shirt_\[generated\].jpg --mask-prompt "(shirt|t-shirt|blue shirt){*2}" --init-image-strength 0.0 --prompt-strength 15 --steps 30
```
