### ISSUE TITLE
Add aliases to model names to make them more consistent

### ISSUE THREAD

**Issue by mqudsi** [brycedrennan/imaginAIry#387]
When using `aimg` or `imagine` directly, it's easy to get the various model names confused because of how many different naming conventions there are. It would be nice if there could be consistently named aliases for all the default models so that one doesn't mix up the name of one model with the naming convention of the other.

In case the naming convention issue isn't clear, these are (some) actual default out-of-the-box model names:
* SD-2.0
* SD-2.0-v
* openjourney-v2
* sd21v

You can see that some names are lowercase, some names are mixed upper/lower case, some names have dashes, some names have no separator between the words/components, some names use `.0` while others don't, some tack on a `v` before the version number and others just use the version number directly, etc.

I propose that in addition to supporting the actual model names above, imaginairy also uses a simple string-to-string dictionary to implement a very rudimentary form of alias support, allowing a consistent naming convention to be used (doesn't matter which one, but it should be lowercase; my personal preference would be `[name]-vX[.Y][-extra]` where `X` is the major version number, `Y` is the minor version number and is omitted when it is `0`). 

(The inconsistencies in model names further exacerbate the issue described in #386 and cause one to crash `aimg` far more often than is desired.)

**Comment by brycedrennan** [comment]
Great catch, model names are no longer case sensitive and I've added a bunch of aliases for the models.
This is in the yet-to-be-released version. 

But also I've removed support for SD 2.0 and 2.1 (in anticipation of supporting SDXL)
