### ISSUE TITLE
`aimg` prompt/line history is sometimes lost

### ISSUE THREAD

**Issue by mqudsi** [brycedrennan/imaginAIry#388]
In case `aimg` encounters a fatal error caused by an exception, I would suggest that either `except: ... raise` or `finally:` be used as an opportunity to save the prompt/line history cache. Currently, if `aimg` crashes the prompt history might be saved or might be lost (I've seen it both ways).

Separately, I have observed on some occasions that `exit` or `quit` may somehow complete either without the line history being flushed to disk or before the line history finishes being flushed to disk such that on subsequent run of `aimg`, the history from the prior session is lost. I don't have a reproducer though, so this would need more investigation.

**Comment by brycedrennan** [comment]
Thanks for the report.  I've made some small improvements to error handling in the cli but I would guess this problem still fundamentally remains.

**Comment by brycedrennan** [comment]
I've improved the error handling so things shouldn't crash out of the program. Let me know if you still have an issue with this.

**Comment by mqudsi** [comment]
Cheers!
