### ISSUE TITLE
How to debug ModuleNotFoundError: No module named 'imaginairy'

### ISSUE THREAD

**Issue by r3econ** [brycedrennan/imaginAIry#390]
I followed the instructions and installed `imaginairy` on my mac (`Ventura 13.5.2 (22G91)`)
However, I am getting an error when I try to execute `imagine "a dog"`:

How would I go about debugging it?
 
```
imagine "a dog"
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 3, in <module>
    import imaginairy.cli.imagine
ModuleNotFoundError: No module named 'imaginairy'
```

The `/opt/homebrew/bin/imagine` script has the following content:

```
#!/opt/homebrew/opt/python@3.10/bin/python3.10
# -*- coding: utf-8 -*-
import imaginairy.cli.imagine

if __name__ == "__main__":
    import imaginairy.cli.main
    imaginairy.cli.imagine.imagine_cmd()
```

**Comment by brycedrennan** [comment]
i don't know. try installing it in a virtual environment?
