### ISSUE TITLE
ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' 

### ISSUE THREAD

**Issue by barsaant** [brycedrennan/imaginAIry#391]
imagine --gif "a flower"

ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (/opt/homebrew/lib/python3.11/site-packages/transformers/utils/hub.py) 

aimg system-info 

imaginairy_version:            11.0.0
imaginairy_path:               /opt/homebrew/lib/python3.11/site-packages/imaginairy
python_version:                3.11.6
python_installation_path:      /opt/homebrew/opt/python@3.11/bin/python3.11
device:                        mps:0
torch_version:                 2.1.1
platform:                      darwin
hardware_description:          macOS-14.0-arm64-arm-64bit
ram_gb:                        8.0
graphics_card:                 Apple MPS

**Comment by brycedrennan** [comment]
Thanks for the info. imaginairy is being rewritten so hopefully this gets resolved in the next version.

**Comment by brycedrennan** [comment]
but also I see you're using an old version of imaginairy. updating will fix this.
