### ISSUE TITLE
Can't use cuda

### ISSUE THREAD

**Issue by sapbotgit** [brycedrennan/imaginAIry#398]
i have NVIDIA GeForce GTX 1060 but in device there is only cpu

`🤖🧠> system-info
imaginairy_version:            13.2.0
imaginairy_path:               C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\imaginairy
python_version:                3.10.0
python_installation_path:      C:\Users\New\AppData\Local\Programs\Python\Python310\python.exe
device:                        cpu
torch_version:                 1.13.1+cpu
platform:                      win32
hardware_description:          Windows-10-10.0.22621-SP0
ram_gb:                        7.96
🤖🧠>`

**Comment by brycedrennan** [comment]
The torch version you have installed says its for `1.13.1+cpu`.  I'm not sure how exactly to install a different version but you'll need to do that.
