### ISSUE TITLE
CLI option to select model

### ISSUE THREAD

**Issue by skorokithakis** [brycedrennan/imaginAIry#40]
I have created a model with Textual Inversion, and I was wondering if there can be an easy CLI option to select the model to generate from?

**Comment by brycedrennan** [comment]
I haven’t played with textual inversion. I assume your model is a small file added to the initial large model. Is that right?

**Comment by skorokithakis** [comment]
I think no, it's a 2 GB ckpt file that I think replaces the original model. I'm trying to see if I can add the option myself, but my GPU has very little VRAM so I can either have the windowing system loaded or run the script, which makes development hard...

**Comment by skorokithakis** [comment]
Looks like simply changing `ckpt_path` in `load_model_from_config` to the path of my model does the trick.

**Comment by skorokithakis** [comment]
I don't know how you want to handle passing the option from the CLI into that function, though.

**Comment by brycedrennan** [comment]
Thanks for the idea. I just pushed out 2.3.0 which lets you specify the model via `--model-weights-path`

**Comment by skorokithakis** [comment]
Thank you!
