### ISSUE TITLE
Error: No such command 'videogen'.

### ISSUE THREAD

**Issue by andzejsp** [brycedrennan/imaginAIry#400]
conda create -n sdv python=3.9
conda activate sdv
pip install imaginairy
```
(sdv) E:\Git_repos\sdv>aimg videogen --model svd_xt --num-frames 120 --num-steps 20 --fps 30 --motion-amount 50 --start-image ./m.jpg --output_folder ./test/
C:\Users\xxxxxx\miniconda3\envs\sdv\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_config_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Usage: aimg [OPTIONS] COMMAND [ARGS]...
Try 'aimg --help' for help.

Error: No such command 'videogen'.

(sdv) E:\Git_repos\sdv>
```

**Comment by brycedrennan** [comment]
videogen is only in the beta version so you have to specify the version: `pip install "imaginairy==14.0.0b2"`

**Comment by andzejsp** [comment]
> videogen is only in the beta version so you have to specify the version: `pip install "imaginairy==14.0.0b2"`

still not working
```
(E:\Git_repos\svd\svd310) E:\Git_repos\svd>aimg videogen --model svd_xt --num-frames 120 --num-steps 20 --fps 30 --motion-amount 50 --start-image ./m.jpg --output_folder ./
Generating video from image ./m.jpg
Device: cpu seed: 325730
Traceback (most recent call last):
  File "E:\Git_repos\svd\svd310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Git_repos\svd\svd310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Git_repos\svd\svd310\Scripts\aimg.exe\__main__.py", line 7, in <module>
  File "E:\Git_repos\svd\svd310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "E:\Git_repos\svd\svd310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "E:\Git_repos\svd\svd310\lib\site-packages\click_shell\core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "E:\Git_repos\svd\svd310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Git_repos\svd\svd310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\Git_repos\svd\svd310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\Git_repos\svd\svd310\lib\site-packages\imaginairy\cli\videogen.py", line 77, in videogen_cmd
    generate_video(
  File "E:\Git_repos\svd\svd310\lib\site-packages\imaginairy\video_sample.py", line 55, in generate_video
    torch.cuda.reset_peak_memory_stats()
  File "E:\Git_repos\svd\svd310\lib\site-packages\torch\cuda\memory.py", line 307, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'

(E:\Git_repos\svd\svd310) E:\Git_repos\svd>

```

and why it does not use GPU? i got 3090

**Comment by brycedrennan** [comment]
I haven't figured out how to get it to install the proper version of torch automatically. until then you can install following instructions here: https://pytorch.org/get-started/locally/

**Comment by evoluder** [comment]
tried doing the above, torch seems to install fine using the link you provided (https://pytorch.org/get-started/locally/) even though pip complains (doing import torch; torch.cuda.is_available(); returns TRUE); however, when i run 'pip install imaginairy' it uninstall torch+cu118 and reinstalls the older version same as the original reporter.

how can i just build the binary pip is distributing? tricking pip into doing what i want seems futile.

**Comment by evoluder** [comment]
Some more context about what pip complained about:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imaginairy 13.2.0 requires torch<2.0.0,>=1.13.1, but you have torch 2.1.2+cu118 which is incompatible.
xformers 0.0.16 requires torch==1.13.1, but you have torch 2.1.2+cu118 which is incompatible.
Successfully installed torch-2.1.2+cu118 torchvision-0.16.2+cu118

**Comment by evoluder** [comment]
Tried to also use the exact version you specified along with the torch install command:

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 "imaginairy==14.0.0b2"

Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in c:\users\anon\appdata\local\programs\python\python310\lib\site-packages (2.1.2+cu118)
Requirement already satisfied: torchvision in c:\users\anon\appdata\local\programs\python\python310\lib\site-packages (0.16.2+cu118)
Requirement already satisfied: torchaudio in c:\users\anon\appdata\local\programs\python\python310\lib\site-packages (2.1.2+cu118)
ERROR: Could not find a version that satisfies the requirement imaginairy==14.0.0b2 (from versions: none)
ERROR: No matching distribution found for imaginairy==14.0.0b2

**Comment by brycedrennan** [comment]
Looking at this now.

**Comment by brycedrennan** [comment]
14.0 is out of beta now so you shouldn't need to specify the exact version. 

It should suffice to `pip install imaginairy --upgrade`

in one part of your output it says you're using `imaginairy 13.2.0` which does not have videogen.

**Comment by brycedrennan** [comment]
So I would 
1) install torch from pytorch.org so it has the right cuda drivers
2) `pip install imaginairy --upgrade`. confirm that it installed >=14
3) run `aimg system-info` to show version information and whether cuda is working
4) try to generate an image `imagine fruit`

**Comment by brycedrennan** [comment]
Okay I just released 4.1.0 - no idea whether it will help but it does have fewer dependencies, so it's possible. Let me know if it still doesnt work and I'm willing to look into this more.

**Comment by evoluder** [comment]
hmm, i forgot to install cuda in this environment, doing that first then trying again

conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

pip install imaginairy --upgrade

same result :/ also these weird error messages 

aimg version
C:\Users\anon\anaconda3\envs\imagine\lib\site-packages\pydantic\_internal\_fields.py:149: UserWarning: Field "model_config_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
13.2.0

i suppose i can delete this environment and try once again, but about to give up on this one. i got it working as version 13.2 on the cpu only, so there's that i guess!

**Comment by brycedrennan** [comment]
This is all great feedback. I know what the warning is and that's something I should address, but harmless.  I'm happy to do a screenshare to debug this right now if you want.  But also understandable if you just want to give up
Video chat: https://meet.google.com/agi-trdc-fog

**Comment by brycedrennan** [comment]
I added testing for windows and conda installation and fixed some issues. Might work now in 14.1.1.  Will re-open if I hear its still broken.
