### ISSUE TITLE
using RAM instead of vram

### ISSUE THREAD

**Issue by sesek3** [brycedrennan/imaginAIry#407]
I have 16GB of ram and 3060m 6gb of vram, heard its possible to run it on 6gb but upon running videogen under linux got out of memory  warnings and it's crashing:
```
aimg videogen --start-image pearl-girl.png --model svd --num-frames 4 -r 5
Generating video from image pearl-girl.png
Device: cuda seed: 777925
[1]    388997 terminated  aimg videogen --start-image pearl-girl.png --model svd --num-frames 4 -r 5
```
I see it uses only system memory and vram remains unused when checked with nvidia-smi. CUDA is pressent:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0
```

**Comment by brycedrennan** [comment]
Yeah probably need to install torch from https://pytorch.org/get-started/locally/

I haven't figured out how to automate that yet.

**Comment by sesek3** [comment]
unfortunately no, got 2.1.0 upgraded to 2.1.1 and still same thing

**Comment by brycedrennan** [comment]
Yeah my previous advice was wrong. The output states you have torch connected to cuda. 
Yes it also uses a lot of Ram. Honestly with 6gb vram its probably not worth running.
