### ISSUE TITLE
CLIP Interrogation - possible solution found

### ISSUE THREAD

**Issue by hmillerbakewell** [brycedrennan/imaginAIry#41]
Under `Todo > Image Enhancement > image describe feature` in the Readme is an entry for "https://github.com/pharmapsychotic/clip-interrogator (blip + clip)"

The ability to pass an image and phrases to CLIP is already present as `enhancers.describe_image_clip.find_img_text_similarity`. The ability to use BLIP is already marked as done on the Todo list. The only remaining part of the `pharmapsychotic/clip-interrogator` code that is not implement here is the long lists of artists, mediums, etc..

There is a package on pypi called `clip-gaze` that includes cleaned and expanded upon versions of those lists (as well as implementing a version of `find_img_text_similarity`). It has no dependencies beyond what is already needed in this repo.

If the lists are desirable I suggest importing them from `clip_gaze`, and if not then I think that part of the Todo can be checked off.

**Comment by brycedrennan** [comment]
I'm hesitant to introduce the dependency just to load what are essentially text files. I haven't implemented yet because I'm unhappy with how long the analysis takes.

**Comment by brycedrennan** [comment]
I spent a bit of time playing with various clip interrogators and I don't find them accurate enough to include in this library.
