### ISSUE TITLE
note for install docs

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#42]
just setting up a brand new M1 mac out of box.. and as well as noted requirements, i.e.:
-homebrew
-python3/pip3
-rust

found that
sudo pip3 install setuptools-rust

was required for the  pip installation of imaginairy to be able to do its 'rust things'..

BTW I previously had imaginairy running (and working!) on a 2015 i7 intel Macbook Pro.. granted it took 15 mins to do a 40 step 'imagine' but I thought that it worked at all was a minor miracle! :-)

**Comment by brycedrennan** [comment]
Ha that's good to know it can work on just a CPU.  Thanks for the heads up. I've updated the readme.
