### ISSUE TITLE
OpenDalle

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#429]
Any chance this can be part of imaginAIry? Might be better than SDXL at this point.

https://huggingface.co/dataautogpt3/OpenDalleV1.1

**Comment by brycedrennan** [comment]
Looks like it's just a finetune of SDXL so might "just work" with sdxl integrate. I just got SDXL working last night.

**Comment by bluusun** [comment]
Wow that is awesome news!

**Comment by brycedrennan** [comment]
![026661_100000002_ddim50_PS7 5_a_flower_ generated](https://github.com/brycedrennan/imaginAIry/assets/1217531/4de2af94-3fce-4328-a741-bc7c0be053f9)
works! this is opendalle 1.1

**Comment by brycedrennan** [comment]
they look very similar to sdxl generations. maybe better. hard to say

**Comment by bluusun** [comment]
In my samples they looked MUCH better than SDXL especially when people are shown.

**Comment by brycedrennan** [comment]
using the same seed? maybe the negative prompt Im using is helping them look similar

**Comment by bluusun** [comment]
Same Seed, negative prompt and positive prompt.

**Comment by brycedrennan** [comment]
![image](https://github.com/brycedrennan/imaginAIry/assets/1217531/ab3ce870-d665-4014-9ca0-6af6f0b16bac)

**Comment by bluusun** [comment]
Looks like a SD1.5 to SD2.0 step up to me. But might be subjective...

**Comment by bluusun** [comment]
Thanks for the release!!! How hard/ how long will it be for Controlnet/ Masks support for SDXL/OpenDALLE?

**Comment by brycedrennan** [comment]
Added in just released 14.0.0
