### ISSUE TITLE
fix-faces difference after 2.2.0

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#43]
the example in readme:
imagine "a couple smiling" --steps 40 --seed 1 --fix-faces
now no longer yields results as shown unless changed to:
imagine "a couple smiling" --steps 40 --seed 1 --fix-faces --fix-faces-fidelity 0

so not sure if that's intended, or the default value for an unspecified --fix-face-fidelity is wrong, or not working?

**Comment by NiclasEriksen** [comment]
This is probably due to the changes in 48117bbcb11352273cc94602d532fcca2c6bfad8. The default fidelity was also changed from `0.2` to `0.5`, where `0.2` was hardcoded and `0.5` is not the default argument value for `ImaginePrompt`.

**Comment by brycedrennan** [comment]
I did intend to change but I should have just left it alone.  I'll revert back the default to 0.2

**Comment by brycedrennan** [comment]
I set it back to 0.2
