### ISSUE TITLE
Video generation quality issues

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#452]
Ran this but video output looks just bad:

aimg videogen --start-image 4.jpg 

Video of 14 frames generated in 530.59 seconds and saved to outputs/video/000001_svd_779418_6fps_4.mp4

![4](https://github.com/brycedrennan/imaginAIry/assets/65051271/4b69640c-1668-456d-a484-2037224d828a)
![iDB 2024-01-14 at 15 07 02](https://github.com/brycedrennan/imaginAIry/assets/65051271/b8266f7f-b2ff-4e25-a9d1-ae07cc4f3bbb)
![iDB 2024-01-14 at 15 06 54](https://github.com/brycedrennan/imaginAIry/assets/65051271/ef482432-6fde-44db-a215-9d1bc314af99)

Then tried to use diff model to no avail:

aimg videogen --start-image 4.jpg --model sdxl
Generating a 12 frame video from 4.jpg. Device:cuda seed:694418
[Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/imaginairy/None'

aimg videogen --start-image 4.jpg --model opendalle
Generating a 12 frame video from 4.jpg. Device:cuda seed:43268
[Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/imaginairy/None'

Am I missing something?

**Comment by bluusun** [comment]
Ideally the results look closer to this :)

https://github.com/dreamoving/dreamoving-project

**Comment by brycedrennan** [comment]
I agree the video model isn't that good, but that's just the way it is for now. There are not alternative models yet. looks like we need a more useful error message when trying to use the `--model` parameter.
