### ISSUE TITLE
Folder upscale with aimg?

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#468]
img version
14.1.1

aimg uspcale
Usage: aimg [OPTIONS] COMMAND [ARGS]...
Try 'aimg --help' for help.

Error: No such command 'uspcale'.

aimg uspcale /root/work

Usage: aimg [OPTIONS] COMMAND [ARGS]...

🤖🧠 ImaginAIry.

Pythonic generation of images via AI

Options:
--help Show this message and exit.

Commands:
colorize Colorize images using AI.
describe Generate text descriptions of images.
edit Edit an image via AI.
edit-demo Make some fun pre-set edits to input photos.
imagine Generate images via AI.
model-list Print list of available models.
server Run a HTTP API server.
system-info Display system information.
upscale Upscale an image 4x using AI.
version Print the version.
videogen AI generate a video from an image

What am I missing?

**Comment by bluusun** [comment]
Also tried aimg uspcale /root/outputs/generated/*
Usage: aimg [OPTIONS] COMMAND [ARGS]...
Try 'aimg --help' for help.

Error: No such command 'uspcale'.

**Comment by brycedrennan** [comment]
`uspcale`
