### ISSUE TITLE
Remodeling ideas, space detection

### ISSUE THREAD

**Issue by xzitlou** [brycedrennan/imaginAIry#471]
Hello, I'm looking at the kitchen remodeling example, and I wanted to know if I can use some control mode that detects the space and based on this, it can generate new remodeling ideas, perhaps by removing furniture, beds, etc.

```
# generate kitchen remodel ideas
🤖🧠> imagine --control-image kitchen.jpg -w 1024 -h 1024 "{_interior-style_} kitchen" --control-mode depth -r 100 --init-image 0.01 --upscale --steps 35 --caption-text "{prompt}"

```

**Comment by brycedrennan** [comment]
if you mean a control mode that ignores furniture. sounds like something that needs  custom training.  I'm not aware of something like that at the moment. But probably someone somewhere has already done it :-)
