### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by WindowsNT** [brycedrennan/imaginAIry#487]
aimg imagine --control-mode hed --size 1920x1080  --outdir "..."  "Two nice cats in the snow"

This results in 
`UnboundLocalError: cannot access local variable 'init_image_t' where it is not associated with a value
`

The same error occurs with other control modes. Without the --control-mode, it works.
Win11/x64.

Thanks for this, I 'm already using it in my sequencer.

**Comment by brycedrennan** [comment]
What version are you using?

**Comment by WindowsNT** [comment]
14.3.0 I installed using pip.

**Comment by WindowsNT** [comment]
When I use imagine.exe instead, it works correctly. Thanks.
