### ISSUE TITLE
FileNotFoundError: runwayml/stable-diffusion-v1-5/vae (repository not found)

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#488]
These have been removed from HF. So SD1.5 related (i.e. controlnet) now errors out :(

**Comment by bluusun** [comment]
https://huggingface.co/posts/dn6/357701279407928

**Comment by bluusun** [comment]
What repo needs to be updated for this to use the mirror model sources?

**Comment by bluusun** [comment]
File "/usr/local/lib/python3.10/site-packages/imaginairy/utils/model_manager.py", line 285, in load_sd15_pipeline
    ) = load_sd15_diffusers_weights(weights_location, device="cpu")
  File "/usr/local/lib/python3.10/site-packages/imaginairy/utils/model_manager.py", line 508, in load_sd15_diffusers_weights
    vae_weights_path = download_huggingface_weights(base_url=base_url, sub="vae")
  File "/usr/local/lib/python3.10/site-packages/imaginairy/utils/downloads.py", line 147, in download_huggingface_weights

**Comment by WindowsNT** [comment]
Still no solution, even the new model_manager.py is updated.

**Comment by tsehaiB** [comment]
Hey! To fix this locally, just switch it out for the CompVis Stable Diffusion V4, grab the link for the sd-v1-4.ckpt, replace 'blob' with 'resolve' and paste it where the runwayml line shows up in the config.py file. Worked for me.

**Comment by brycedrennan** [comment]
fixed in imaginairy==15.0.0

also added a not very good version of flux that probably only works on linux nvidia 4090s
