### ISSUE TITLE
suggested documentation fixes

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#52]
don't think this is what you intended:

> imagine "a {lime|blue|silver|aqua} colored dog" -r 2 --seed 0 will generate both "a red dog" and "a black dog"

typo eb = be

> imagine "a {_color_} dog" -r 4 --seed 0 will generate four, different colored dogs. The colors will eb pulled from an included phraselist of colors.

Add heading for upgrade/update to point out the obvious for noobs (like me :-P).. i.e

Updating to latest version

use `pip install --upgrade imaginairy` to update to latest version

**Comment by brycedrennan** [comment]
Thanks for pointing that out! I fixed those issues but left out the upgrade instructions as I expect my target audience to already know that or to be able to quickly google it.
