### ISSUE TITLE
openSsl error when running in conda environment

### ISSUE THREAD

**Issue by marcmaxson** [brycedrennan/imaginAIry#56]
I tried a bunch of workarounds but I always get this error if I install /run it in a conda environment:

`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>`

Works fine in my main environment. I think downloading the model from github requires SSL on requests.

**Comment by brycedrennan** [comment]
This has happened previously: https://github.com/brycedrennan/imaginAIry/issues/12

**Comment by brycedrennan** [comment]
I'm guessing you're running this on a work laptop and corporate security is interfering. as described here: https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/disable-ssl-verification.html

As I don't think this is an issue with imaginAIry I'm closing the issue until we get more information
