### ISSUE TITLE
How to switch to GPU mode ?

### ISSUE THREAD

**Issue by ArthurKuhn-prog** [brycedrennan/imaginAIry#66]
Hello !

I've juste installed and started to use ImaginAIry on my laptop and I have a problem.
It seems to be stuck on CPU mode (every time I run it I get the "it's gonna be sloooooooow message").
How can I change that ? Thanks !

I'm running it in the windows Powershell, with a Nvidia GPU, for infos.

**Comment by brycedrennan** [comment]
I haven't ever installed it on windows so I'm sure. The message implies that the software wasn't able to find the CUDA drivers.  What specific graphics card do you have?

**Comment by brycedrennan** [comment]
You might run 
```python
import torch
torch.randn(1).to("cuda")
``` 
and see if you get a more useful error message.

**Comment by brycedrennan** [comment]
Closing until we get more information.

**Comment by UtahDave** [comment]
I'm getting this error. I'm on Windows 11.  Running Python 3.10.7.  I have an nvidia 3080

I ran the the above code and got the following:

```
C:\Users\bouch>python
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.randn(1).to("cuda")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bouch\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by UtahDave** [comment]
Do I have to install the cuda toolkit from nvidia?

**Comment by sebasti1a** [comment]
Yes, you need to install Cuda Toolkit for windows : https://developer.nvidia.com/cuda-downloads
Then re-install Torch for python like this :
```
pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html
```
Finally, you can test if Cuda is active for Torch :
```
import torch
torch.cuda.is_available()
```

**Comment by UtahDave** [comment]
OK, that worked. Thanks!

I didn't see the Cuda toolkit requirement in the imaginairy install instructions.

**Comment by tcgumus** [comment]
That's also worked for me on gtx 1080 ti. Thanks

**Comment by brycedrennan** [comment]
@tcgumus You're saying you're generating images with imaginairy on a 1080 ti in 1.2 seconds? I'm surprised!

**Comment by tcgumus** [comment]
I know realise that it was a defined image for certain options. 
Defaut imagine command takes about 9-14s. It was around 2 to 3 minute before.
