### ISSUE TITLE
minor: filenames and underscore seperators

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#67]
It'd be handy if auto generated filenames could consistently be 'split' on underscores, this is mostly the case, except, e.g.
imagine "cat in an art deco setting. photo realistic by {_artist_}"  --sampler-type k_dpm_2 
creates something like:
000155_458176395_k_dpm_240_PS7.5_cat_in_an_art_deco_setting._photo_realistic_by_saturno_butto_[generated].jpg

where the sampler type itself has underscores (in this case k_dpm_2,  but will be same for k_lms|k_dpm_2|k_dpm_2_a|k_euler|k_euler_a|k_heun) and therefore creates more items in a 'split' (compared to plain plms, ddim etc)..

maybe take underscores out of sampler names all together.. or.. just strip them out before creating filename?

**Comment by brycedrennan** [comment]
Good idea. It shall be done.

**Comment by brycedrennan** [comment]
Included in just released 4.0.0
