### ISSUE TITLE
minor: progress display suggestion

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#69]
another minor suggestion..
with your new lists I'm sometimes using, say, {_artist_} with a -r 40 setting.. 
thus a 'where we're up to' included in progress outputs would be convenient..
something like:

Generating 🖼  : "prompt"
becomes
Generating 🖼  **(x/40)**: "prompt"

or just on the end after, say, sampler-type:k_dpm_2, **repeat:x/40**

I realise that it might not be as simple as it looks due to way prompts + repeats can spawn many variations on the final image counts.. but thought I'd suggest anyway.

**Comment by brycedrennan** [comment]
Seems reasonable.

**Comment by brycedrennan** [comment]
Done. released in 4.1.0
