### ISSUE TITLE
does it work with ubuntu wsl ?

### ISSUE THREAD

**Issue by hfadhloun** [brycedrennan/imaginAIry#71]
I am getting this message : 
CUDA error: no kernel image is available for execution on the device wsl2

thank you

**Comment by brycedrennan** [comment]
Thanks for the report, unfortunately I can't invest the time to support WSL but it looks like others have figured out how to do it, so it should be possible:
https://www.reddit.com/r/StableDiffusion/comments/wygbpj/running_stable_diffusion_on_windows_with_wsl2/
https://aarol.dev/posts/stable-diffusion-windows/
https://www.google.com/search?q=stable+diffusion+wsl2+ubuntu
