### ISSUE TITLE
FR: Add ability to preload models

### ISSUE THREAD

**Issue by watzon** [brycedrennan/imaginAIry#72]
When using this library programatically it can take a bit to load the model the first time, which makes it so that the first image generation takes significantly longer than subsequent ones. It would be nice if there was a way to preload models that you know you're going to be using so that this doesn't happen.

**Comment by brycedrennan** [comment]
When I've encountered this I've just "generated" an image with 2 steps at the beginning. Does that work for your case?

Having to know the inner workings of the library (and which models are loaded) isn't the developer experience I'm going for. It's not as easy as you'd think to identify which models are going to be run beforehand since a lot of models call other models.

**Comment by watzon** [comment]
Maybe I didn't explain the problem well enough. I have a server type situation, a telegram bot, so the program is always running. The first time a checkpoint is loaded it shows a message in the console saying that it's importing the model (or something to that effect) which takes a little bit. After that the checkpoint is already loaded, so everything runs quickly, but the first time it's a little slow.

Just wondering if there exists, or if it could be added, the ability to preload the checkpoint before doing any image gens. Ideally it would be nice to be able to load multiple models into memory if you have enough VRAM, but I'd settle for just one. I know I could just do a dummy gen when the bot starts up, but I figured I'd put this out there anyway.

**Comment by brycedrennan** [comment]
Yeah I mean, I'd hardcode the dummy image generation into the startup of the server.  

If it'll make you feel better you can make a function called `preload_models` that secretly generates the dummy image :-) 

```python
def preload_models():
    p = ImaginePrompt("a computer", steps=3, upscale=True, fix_faces=True)
    result = next(imagine([p]))
```

**Comment by brycedrennan** [comment]
There are more models being loaded behind the scenes than you'd expect so I'd rather not handle this additional complexity when we have this pretty simple work around.

**Comment by brycedrennan** [comment]
Great to hear it's being used. Thanks for checking in. Would love to see the bot but understand if that's not desirable at the moment.

 I would like to eventually support having multiple weight files loaded at the same time but I think I'd need to have some pretty good memory management code to make that user friendly.

**Comment by watzon** [comment]
Yeah it's just for a userbot at the moment. I figured a programatic solution like this would be preferable to using the webui's API. I understand not wanting to add additional complexity though.

**Comment by brycedrennan** [comment]
If you're saying I'm losing a customer to webui's api well then I'll see what I can do :-)

**Comment by watzon** [comment]
Lol the webui would have the same issue where it comes to loading multiple models into memory at least, but I'd love to not have to use a workaround to load a model when the bot starts. I haven't looked at that code myself, but I may do so in the near future and see if I can get a zero-complexity solution into a PR. Thanks for your quick responsiveness though! Great project!

**Comment by brycedrennan** [comment]
It would be relatively straightforward to preload the main diffusion model, if you know which one you'll be using.   It was preloading that model until a few days ago.  So actually, this may get you most of what you want:
```python
get_diffusion_model("SD-1.5")
```
I'm messing with model management right now. I released that function yesterday I think. Trying to integrate the new inpainting model right now.
