### ISSUE TITLE
treating sampler types like lists via command line?

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#73]
just another suggestion..
interesting testing with same prompt + seed with different sampler types led to a thought that having the option for 'each', or 'series' (ddim+plms), or 'random' options on --sampler-type might come in handy..

not sure what syntax would be consistent with command line options but maybe using {} or `_option_` as per prompt syntaxes might work e.g.:
`_each_` = do 1 each of sampler types available (currently 10, thereby creating ten images)
`_random_` = choose 1 sampler randomly
'+ syntax' for 'series' thereby "--sampler-type ddim + plms + k_huen" = step through sampler series list thereby creating three images
or maybe [] easier to parse, e.g. --sampler-type [ddim  plms  k_huen]

not sure, leave as whether a sensible/useful idea, and implementation details, for you to decide :-)

**Comment by brycedrennan** [comment]
This sounds like a more advanced use case then I'd want to support at the command line. I'd suggest just moving to the python interface at that point.

Untested code but you get the idea:
```python
from imaginairy import ImaginePrompt, imagine_image_files
from imaginairy.samplers.base import SAMPLER_TYPE_OPTIONS

def main():
  prompt_text = "a dolphin"
  prompts = []
  for sampler_type in SAMPLER_TYPE_OPTIONS:
      prompt = ImaginePrompt(
          prompt_text, width=512, height=512, steps=20, seed=1, sampler_type=sampler_type
      )
      prompts.append(prompt)
  
  imagine_image_files(prompts, outdir="output")

if __name__ == "__main__":
    main()
```

**Comment by Cybergate9** [comment]
great thanks!

**Comment by Cybergate9** [comment]
incidentally it possible/desirable to suppress the error/warning messages that happen when using script like above?

e.g. it spews out a pile of warnings starting with:
```
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel:
... [ends with]
- This IS expected if you are initializing CLIPTextModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPTextModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

**Comment by brycedrennan** [comment]
```python
from imaginairy.log_utils import configure_logging
configure_logging()
```

**Comment by Cybergate9** [comment]
thanks again! will leave you alone for today :-)

**Comment by brycedrennan** [comment]
yeah no worries - thanks for all the great feedback
