### ISSUE TITLE
steps/iteration problems with k_dpm_adaptive

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#74]
thanks for #73!
when testing that I ran into a problem with k_dpm_fast - it seems to initialise at --steps XX +1?

e.g. imagine "an art deco cat" --sampler-type k_dpm_fast
will run an iteration with 41 steps, not 40

when this happens from #73 example script:
imagine_image_files(prompts, outdir="output")
it looses the plot entirely and just keeps iterating..

**Comment by brycedrennan** [comment]
I'll have to dig into that. If I recall k_dpm_fast and k_dpm_adaptive may ignore the steps parameter entirely.  Other than the # of steps being wrong is it working?

**Comment by Cybergate9** [comment]
umm, when scripted as per your helpful script for #73 it seems to go in to a "forever iterations" conditions..
I can replicate problem with:
```
from imaginairy import ImaginePrompt, imagine_image_files
from imaginairy.samplers.base import SAMPLER_TYPE_OPTIONS

def main():
  prompt_text = "an art deco cat"
  prompts = []
  for sampler_type in ["k_dpm_fast","k_dpm_adaptive"]:
      prompt = ImaginePrompt(
          prompt_text, width=512, height=512, steps=20, seed=1, sampler_type=sampler_type
      )
      prompts.append(prompt)
      print(vars(prompt))
  
  imagine_image_files(prompts, outdir="output")

if __name__ == "__main__":
    main()
```

does that help?

**Comment by Cybergate9** [comment]
even just:

`imagine "an art deco cat" --sampler-type k_dpm_adaptive`

will replicate the problem, so it's with k_dpm_adaptive, not k_dpm_fast, oops, sorry..

**Comment by brycedrennan** [comment]
What OS/python version? it's working for me but adaptive did do 60 steps (ignoring the steps argument)

**Comment by Cybergate9** [comment]
MacOS 12.6, Python 3.10.7, imaginairy in its own py-venv

for me k_dpm_adaptive does weird display too, no progress bar, etc.
e.g. before I ctrl-c (^C), it's reached 153 iterations as per below

```
(py-venv2) shaun@Shauns-MBPro14 dev % imagine "an art deco cat" --sampler-type k_dpm_adaptive
🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: "an art deco cat" 512x512px seed:554043597 prompt-strength:7.5 steps:40 sampler-type:k_dpm_adaptive
Loading model /Users/shaun/.cache/huggingface/transformers/d12e71b67e29abaf317bf9d0e31644872fd2072509a4b3582cbb0c30f70824e9.98fc1312797017a8bac6993df565908fd18f09319b40d9bd35457dfa1459ecf0 onto mps:0 backend...
153it [03:38,  1.43s/it]^C
```

**Comment by brycedrennan** [comment]
I was running it on linux. Trying it on an M1 now.

**Comment by Cybergate9** [comment]
so now I'm getting:
`(py-venv2) shaun@Shauns-MBPro14 dev % imagine "an art deco cat" --sampler-type k_dpm_adaptive
🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: "an art deco cat" 512x512px seed:931973866 prompt-strength:7.5 steps:40 sampler-type:k_dpm_adaptive
Loading model /Users/shaun/.cache/huggingface/transformers/d12e71b67e29abaf317bf9d0e31644872fd2072509a4b3582cbb0c30f70824e9.98fc1312797017a8bac6993df565908fd18f09319b40d9bd35457dfa1459ecf0 onto mps:0 backend...
45it [00:56,  1.26s/it]
    🖼  [generated] saved to: ./outputs/generated/000356_931973866_kdpmadaptive40_PS7.5_an_art_deco_cat_[generated].jpg
(py-venv2) shaun@Shauns-MBPro14 dev % imagine "an art deco cat" --sampler-type k_dpm_adaptive
🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: "an art deco cat" 512x512px seed:49539039 prompt-strength:7.5 steps:40 sampler-type:k_dpm_adaptive
Loading model /Users/shaun/.cache/huggingface/transformers/d12e71b67e29abaf317bf9d0e31644872fd2072509a4b3582cbb0c30f70824e9.98fc1312797017a8bac6993df565908fd18f09319b40d9bd35457dfa1459ecf0 onto mps:0 backend...
54it [01:04,  1.20s/it]
    🖼  [generated] saved to: ./outputs/generated/000357_49539039_kdpmadaptive40_PS7.5_an_art_deco_cat_[generated].jpg
`

looks like I was just unlucky to have it go over 100-150 iterations? 
don't know what 'adaptive' does, so previously it looked like it had gone off into a forever loop, but may not be the case at all.. may have just decided it need that many iterations?

**Comment by brycedrennan** [comment]
The weird progress bar is what happens when it doesn't know how many steps it's going to do.
`imagine "an art deco cat" --sampler-type k_dpm_adaptive --seed 554043597` worked for me after 69 steps.

I'm on MacOS 12.5.1 so maybe that's the difference. Guess we'll see after I update.  In the meantime you might find some clues by adding --show-work to the cmd.  It will go much slower but output a bunch of intermediate images to the `steps` folder.   

I believe adaptive is supposed to do as few or many as needed based on the image quality or something. (I haven't looked into it deeply).

**Comment by brycedrennan** [comment]
I've noticed that occasionally generations on M1 just fail for no reason. Maybe with adaptive it doesn't know to stop after getting into an unrecoverable failure state.

**Comment by Cybergate9** [comment]
ok, thanks, then we can probably close this, as I think it was more my misunderstanding (having never used any 'adaptives') than any actual problem..
sorry for the tail chasing..

**Comment by brycedrennan** [comment]
Well, we should probably do the following:
 - note that adaptive ignores steps in the docs
 - check for the failure case and handle it better
So i'll leave it open for now.

**Comment by Cybergate9** [comment]
Just a note to say - that yes on an M1 (pro), my experience is you get a reasonable number of "just black"s.
I'd be @ a few thousands of generations by now and my _guess_ is the black failure rate might be as high as 5%..
It's not a problem to me, and from my very little understanding it seems entirely reasonable that randomly seeded noise may indeed start off a 'diffusion' that ends up going nowhere..

**Comment by brycedrennan** [comment]
@Cybergate9 you still getting black images on latest version? I have been unable to reproduce it now. Maybe something else I fixed helped?

**Comment by Cybergate9** [comment]
no, no blacks for a while now, now I come to think of it, since.. ummm.. not sure, possibly the update circa 4.x so could have been code or maybe change to SD-1.5.. either way all going swimmingly.

couple of other positive observations:

1) v5.0.0 on my m1 pro (8-cpu, 14-gpu) 'standard' prompt (so allowing all new defaults including sampler-type) is generating at approx 30 secs per image instead of previously circa 50 secs per image - so big improvement there  thanks :-)

just running `imagine "an art deco cat" --sampler-type k_dpm_adaptive -r 50`
so far 14 in, and not getting any high count iterations (so far range 45-69 iterations, no silly 100-150 instances) so I think that your change to default 15 steps for that sampler has sorted that out too

**Comment by brycedrennan** [comment]
great - thank you
