### ISSUE TITLE
k_dpm_fast seemingly not working

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#75]
1) steps always runs --steps XX + 1 (no idea whether related)
2) images always just 'large blob noise', e.g.
![000356_1_kdpmfast40_PS7 5_treeing_walker_coonhound_by_zhang_kechun_ generated](https://user-images.githubusercontent.com/11902848/197711723-93bd1afd-ba38-46ad-9d03-3e683409abc1.jpg)

my replicate test was:
`imagine "{_animal_} by {_artist_}" -r 10 --sampler-type k_dpm_fast --seed 1`

(machinery: Imaginairy release 4.1, M1 Pro, MacOS 12.6, Python 3.10.7 in py-venv)

**Comment by brycedrennan** [comment]
Confirmed

**Comment by brycedrennan** [comment]
Fixed in just released 5.0.0
