### ISSUE TITLE
minor: maybe just clarification (prompt weights)

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#77]
I see:
```
ImaginePrompt([
        WeightedPrompt("cat", weight=1),
        WeightedPrompt("dog", weight=1),
    ]),
```
in examples, by can't quite figure out a couple of things:
- how are these specified in command line prompts? (e.g. (dog,weight=1) or (dog:1) or something?)
- are weights similar to mask weights e.g. 0->1?

thanks in advance

**Comment by brycedrennan** [comment]
They cannot be specified at the command line. 
The weights are relative to eachother.  

```
WeightedPrompt("cat", weight=1),
        WeightedPrompt("dog", weight=1),
```
is the same as 
```
WeightedPrompt("cat", weight=234),
        WeightedPrompt("dog", weight=234),
```

**Comment by Cybergate9** [comment]
ah ok, understand, thanks..

related: I see reference elsewhere to syntax such as (word) , or ((word)) in prompts, which implies some sort or weighting, biasing, strengthening, or whatever terminology one might use..

Are you aware of whether this is implemented in stable diffusion's tx2img (i.e work in imaginairy because of that fact) or is specific to a particular implementation?

**Comment by brycedrennan** [comment]
I believe that is implemented here: 
https://github.com/AUTOMATIC1111/stable-diffusion-webui
and probably here as well
https://github.com/Sygil-Dev/sygil-webui

I should implement something similar but haven't found the time yet.

**Comment by Cybergate9** [comment]
no problems, thanks!
if one really needs/wants to use weights we ('the users' :-P) can revert to python, or indeed create our own python wrapper which mimics () (()) type behaviour and feeding that into imaginairy's code as weighted prompts

thanks again :-)
