### ISSUE TITLE
Can it be faster on M1 machine? Torch update 

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#79]
I am wondering if it could run a bit faster on M1 machine with latest PyTorch?
https://pytorch.org/blog/PyTorch-1.13-release

Also, "Loading mode" part seems to be slow and need to run each time, can this step also be skipped?

**Comment by brycedrennan** [comment]
if you run `aimg` at the command line you'll get a persistent console you can generate images from without reloading the model every time.

**Comment by brycedrennan** [comment]
Yes let me know if the new pytorch is faster. The library doesn't restrict you from using newer versions.
