### ISSUE TITLE
Work going by default to my cpu instead of my gpu

### ISSUE THREAD

**Issue by greggameplayer** [brycedrennan/imaginAIry#93]
Hello,
how can i in commandline execution make that imaginairy use my RTX 2070 instead of my cpu ?

**Comment by brycedrennan** [comment]
if you have a compatible graphics card and CUDA installed, it will automatically use it.  It only uses the cpu if https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html returns False

Probably something about your graphics card isn't setup right.

**Comment by greggameplayer** [comment]
@brycedrennan Ok it was because i'm using conda and i needed to install cuda pytorch version with cuda toolkit directly on python with this command : 
`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`

**Comment by xrd** [comment]
I've been able to run multiple other docker containers on the GPU but this isn't working. Perhaps something to do this the issue described here:

https://github.com/fboulnois/stable-diffusion-docker/issues/22#issuecomment-1277249400
