### ISSUE TITLE
integrate stable diffusion 2.0

### ISSUE THREAD

**Issue by brycedrennan** [brycedrennan/imaginAIry#95]
https://github.com/Stability-AI/stablediffusion

**Comment by rcarmo** [comment]
Will there be a way to pick the model version being used? There are some pretty substantial differences in the built-in styles that may make it useful to "revert" as required.

**Comment by rcarmo** [comment]
Belay that, spotted `--model SD-1.5`

**Comment by brycedrennan** [comment]
Yeah I might end up leaving the default at 1.5. 2.0 base isn't a clear improvement

**Comment by rcarmo** [comment]
Quick question: how do I switch the model programmatically (like when running this inside JupyterLab?) Do I need to explicitly unload and reload another model?

**Comment by brycedrennan** [comment]
It will switch itself when a prompt comes in with a different model.
