### ISSUE TITLE
Error on imaginairy==6.0.0a0 Mac M1 Max

### ISSUE THREAD

**Issue by mattpang** [brycedrennan/imaginAIry#97]
Using `pip install imaginairy==6.0.0a0` on MacBook Pro M1 Max

prompt, doesn't matter fails on any prompt: `imagine "a scenic landscape in a watercolour style artstation"`

`/miniforge3/lib/python3.9/site-packages/imaginairy/vendored/k_diffusion/external.py", line 97, in t_to_sigma
    log_sigma = (1 - w) * self.log_sigmas[low_idx] + w * self.log_sigmas[high_idx]`

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by brycedrennan** [comment]
checking on this

**Comment by brycedrennan** [comment]
working for me on M1 Max.  I would guess it's because you're running it with conda.
