### ISSUE TITLE
Is it possible to do manual infilling?

### ISSUE THREAD

**Issue by johtso** [brycedrennan/imaginAIry#98]
Is it possible to supply a starting image with certain portions removed, and have those areas filled (a la dall-e)?

**Comment by brycedrennan** [comment]
You can provide a separate mask image.  Example from the tests: 
https://github.com/brycedrennan/imaginAIry/blob/master/tests/test_api.py#L201-L214

**Comment by AntouanK** [comment]
@brycedrennan 
I tried making a mask, exact same dimensions, tried both png and jpg, and I get this error.

![2022-11-24_21-22](https://user-images.githubusercontent.com/4569111/203864536-dc50348f-8c97-4183-adaa-97fc8fb2f5a1.png)

any idea why?

( mask images where made with figma, using only black and white colors )

**Comment by johtso** [comment]
I wonder if it might be worth adding a flag to derive a mask from the transparent parts of the initial image?

**Comment by brycedrennan** [comment]
@AntouanK  I'd guess the colorspace of the images don't match.  I'd consider that bug if you want to open a new issue.

**Comment by brycedrennan** [comment]
@johtso yeah that could be nice. I would welcome a pull request that does that.
